<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Currency;
use App\Models\Language;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * [name, iso2, iso3, phone_code] for every ISO 3166-1 country. Flag
     * emoji is derived from iso2 (regional indicator symbols) instead of
     * being hand-typed per row.
     */
    private const COUNTRIES = [
        ['Afghanistan', 'AF', 'AFG', '+93'],
        ['Albania', 'AL', 'ALB', '+355'],
        ['Algeria', 'DZ', 'DZA', '+213'],
        ['Andorra', 'AD', 'AND', '+376'],
        ['Angola', 'AO', 'AGO', '+244'],
        ['Antigua and Barbuda', 'AG', 'ATG', '+1268'],
        ['Argentina', 'AR', 'ARG', '+54'],
        ['Armenia', 'AM', 'ARM', '+374'],
        ['Australia', 'AU', 'AUS', '+61'],
        ['Austria', 'AT', 'AUT', '+43'],
        ['Azerbaijan', 'AZ', 'AZE', '+994'],
        ['Bahamas', 'BS', 'BHS', '+1242'],
        ['Bahrain', 'BH', 'BHR', '+973'],
        ['Bangladesh', 'BD', 'BGD', '+880'],
        ['Barbados', 'BB', 'BRB', '+1246'],
        ['Belarus', 'BY', 'BLR', '+375'],
        ['Belgium', 'BE', 'BEL', '+32'],
        ['Belize', 'BZ', 'BLZ', '+501'],
        ['Benin', 'BJ', 'BEN', '+229'],
        ['Bhutan', 'BT', 'BTN', '+975'],
        ['Bolivia', 'BO', 'BOL', '+591'],
        ['Bosnia and Herzegovina', 'BA', 'BIH', '+387'],
        ['Botswana', 'BW', 'BWA', '+267'],
        ['Brazil', 'BR', 'BRA', '+55'],
        ['Brunei', 'BN', 'BRN', '+673'],
        ['Bulgaria', 'BG', 'BGR', '+359'],
        ['Burkina Faso', 'BF', 'BFA', '+226'],
        ['Burundi', 'BI', 'BDI', '+257'],
        ['Cabo Verde', 'CV', 'CPV', '+238'],
        ['Cambodia', 'KH', 'KHM', '+855'],
        ['Cameroon', 'CM', 'CMR', '+237'],
        ['Canada', 'CA', 'CAN', '+1'],
        ['Central African Republic', 'CF', 'CAF', '+236'],
        ['Chad', 'TD', 'TCD', '+235'],
        ['Chile', 'CL', 'CHL', '+56'],
        ['China', 'CN', 'CHN', '+86'],
        ['Colombia', 'CO', 'COL', '+57'],
        ['Comoros', 'KM', 'COM', '+269'],
        ['Congo (Congo-Brazzaville)', 'CG', 'COG', '+242'],
        ['Congo (DRC)', 'CD', 'COD', '+243'],
        ['Costa Rica', 'CR', 'CRI', '+506'],
        ['Croatia', 'HR', 'HRV', '+385'],
        ['Cuba', 'CU', 'CUB', '+53'],
        ['Cyprus', 'CY', 'CYP', '+357'],
        ['Czechia', 'CZ', 'CZE', '+420'],
        ['Denmark', 'DK', 'DNK', '+45'],
        ['Djibouti', 'DJ', 'DJI', '+253'],
        ['Dominica', 'DM', 'DMA', '+1767'],
        ['Dominican Republic', 'DO', 'DOM', '+1809'],
        ['Ecuador', 'EC', 'ECU', '+593'],
        ['Egypt', 'EG', 'EGY', '+20'],
        ['El Salvador', 'SV', 'SLV', '+503'],
        ['Equatorial Guinea', 'GQ', 'GNQ', '+240'],
        ['Eritrea', 'ER', 'ERI', '+291'],
        ['Estonia', 'EE', 'EST', '+372'],
        ['Eswatini', 'SZ', 'SWZ', '+268'],
        ['Ethiopia', 'ET', 'ETH', '+251'],
        ['Fiji', 'FJ', 'FJI', '+679'],
        ['Finland', 'FI', 'FIN', '+358'],
        ['France', 'FR', 'FRA', '+33'],
        ['Gabon', 'GA', 'GAB', '+241'],
        ['Gambia', 'GM', 'GMB', '+220'],
        ['Georgia', 'GE', 'GEO', '+995'],
        ['Germany', 'DE', 'DEU', '+49'],
        ['Ghana', 'GH', 'GHA', '+233'],
        ['Greece', 'GR', 'GRC', '+30'],
        ['Grenada', 'GD', 'GRD', '+1473'],
        ['Guatemala', 'GT', 'GTM', '+502'],
        ['Guinea', 'GN', 'GIN', '+224'],
        ['Guinea-Bissau', 'GW', 'GNB', '+245'],
        ['Guyana', 'GY', 'GUY', '+592'],
        ['Haiti', 'HT', 'HTI', '+509'],
        ['Honduras', 'HN', 'HND', '+504'],
        ['Hong Kong', 'HK', 'HKG', '+852'],
        ['Hungary', 'HU', 'HUN', '+36'],
        ['Iceland', 'IS', 'ISL', '+354'],
        ['India', 'IN', 'IND', '+91'],
        ['Indonesia', 'ID', 'IDN', '+62'],
        ['Iran', 'IR', 'IRN', '+98'],
        ['Iraq', 'IQ', 'IRQ', '+964'],
        ['Ireland', 'IE', 'IRL', '+353'],
        ['Israel', 'IL', 'ISR', '+972'],
        ['Italy', 'IT', 'ITA', '+39'],
        ['Jamaica', 'JM', 'JAM', '+1876'],
        ['Japan', 'JP', 'JPN', '+81'],
        ['Jordan', 'JO', 'JOR', '+962'],
        ['Kazakhstan', 'KZ', 'KAZ', '+7'],
        ['Kenya', 'KE', 'KEN', '+254'],
        ['Kiribati', 'KI', 'KIR', '+686'],
        ['Kuwait', 'KW', 'KWT', '+965'],
        ['Kyrgyzstan', 'KG', 'KGZ', '+996'],
        ['Laos', 'LA', 'LAO', '+856'],
        ['Latvia', 'LV', 'LVA', '+371'],
        ['Lebanon', 'LB', 'LBN', '+961'],
        ['Lesotho', 'LS', 'LSO', '+266'],
        ['Liberia', 'LR', 'LBR', '+231'],
        ['Libya', 'LY', 'LBY', '+218'],
        ['Liechtenstein', 'LI', 'LIE', '+423'],
        ['Lithuania', 'LT', 'LTU', '+370'],
        ['Luxembourg', 'LU', 'LUX', '+352'],
        ['Madagascar', 'MG', 'MDG', '+261'],
        ['Malawi', 'MW', 'MWI', '+265'],
        ['Malaysia', 'MY', 'MYS', '+60'],
        ['Maldives', 'MV', 'MDV', '+960'],
        ['Mali', 'ML', 'MLI', '+223'],
        ['Malta', 'MT', 'MLT', '+356'],
        ['Marshall Islands', 'MH', 'MHL', '+692'],
        ['Mauritania', 'MR', 'MRT', '+222'],
        ['Mauritius', 'MU', 'MUS', '+230'],
        ['Mexico', 'MX', 'MEX', '+52'],
        ['Micronesia', 'FM', 'FSM', '+691'],
        ['Moldova', 'MD', 'MDA', '+373'],
        ['Monaco', 'MC', 'MCO', '+377'],
        ['Mongolia', 'MN', 'MNG', '+976'],
        ['Montenegro', 'ME', 'MNE', '+382'],
        ['Morocco', 'MA', 'MAR', '+212'],
        ['Mozambique', 'MZ', 'MOZ', '+258'],
        ['Myanmar', 'MM', 'MMR', '+95'],
        ['Namibia', 'NA', 'NAM', '+264'],
        ['Nauru', 'NR', 'NRU', '+674'],
        ['Nepal', 'NP', 'NPL', '+977'],
        ['Netherlands', 'NL', 'NLD', '+31'],
        ['New Zealand', 'NZ', 'NZL', '+64'],
        ['Nicaragua', 'NI', 'NIC', '+505'],
        ['Niger', 'NE', 'NER', '+227'],
        ['Nigeria', 'NG', 'NGA', '+234'],
        ['North Korea', 'KP', 'PRK', '+850'],
        ['North Macedonia', 'MK', 'MKD', '+389'],
        ['Norway', 'NO', 'NOR', '+47'],
        ['Oman', 'OM', 'OMN', '+968'],
        ['Pakistan', 'PK', 'PAK', '+92'],
        ['Palau', 'PW', 'PLW', '+680'],
        ['Palestine', 'PS', 'PSE', '+970'],
        ['Panama', 'PA', 'PAN', '+507'],
        ['Papua New Guinea', 'PG', 'PNG', '+675'],
        ['Paraguay', 'PY', 'PRY', '+595'],
        ['Peru', 'PE', 'PER', '+51'],
        ['Philippines', 'PH', 'PHL', '+63'],
        ['Poland', 'PL', 'POL', '+48'],
        ['Portugal', 'PT', 'PRT', '+351'],
        ['Qatar', 'QA', 'QAT', '+974'],
        ['Romania', 'RO', 'ROU', '+40'],
        ['Russia', 'RU', 'RUS', '+7'],
        ['Rwanda', 'RW', 'RWA', '+250'],
        ['Saint Kitts and Nevis', 'KN', 'KNA', '+1869'],
        ['Saint Lucia', 'LC', 'LCA', '+1758'],
        ['Saint Vincent and the Grenadines', 'VC', 'VCT', '+1784'],
        ['Samoa', 'WS', 'WSM', '+685'],
        ['San Marino', 'SM', 'SMR', '+378'],
        ['Sao Tome and Principe', 'ST', 'STP', '+239'],
        ['Saudi Arabia', 'SA', 'SAU', '+966'],
        ['Senegal', 'SN', 'SEN', '+221'],
        ['Serbia', 'RS', 'SRB', '+381'],
        ['Seychelles', 'SC', 'SYC', '+248'],
        ['Sierra Leone', 'SL', 'SLE', '+232'],
        ['Singapore', 'SG', 'SGP', '+65'],
        ['Slovakia', 'SK', 'SVK', '+421'],
        ['Slovenia', 'SI', 'SVN', '+386'],
        ['Solomon Islands', 'SB', 'SLB', '+677'],
        ['Somalia', 'SO', 'SOM', '+252'],
        ['South Africa', 'ZA', 'ZAF', '+27'],
        ['South Korea', 'KR', 'KOR', '+82'],
        ['South Sudan', 'SS', 'SSD', '+211'],
        ['Spain', 'ES', 'ESP', '+34'],
        ['Sri Lanka', 'LK', 'LKA', '+94'],
        ['Sudan', 'SD', 'SDN', '+249'],
        ['Suriname', 'SR', 'SUR', '+597'],
        ['Sweden', 'SE', 'SWE', '+46'],
        ['Switzerland', 'CH', 'CHE', '+41'],
        ['Syria', 'SY', 'SYR', '+963'],
        ['Taiwan', 'TW', 'TWN', '+886'],
        ['Tajikistan', 'TJ', 'TJK', '+992'],
        ['Tanzania', 'TZ', 'TZA', '+255'],
        ['Thailand', 'TH', 'THA', '+66'],
        ['Timor-Leste', 'TL', 'TLS', '+670'],
        ['Togo', 'TG', 'TGO', '+228'],
        ['Tonga', 'TO', 'TON', '+676'],
        ['Trinidad and Tobago', 'TT', 'TTO', '+1868'],
        ['Tunisia', 'TN', 'TUN', '+216'],
        ['Turkey', 'TR', 'TUR', '+90'],
        ['Turkmenistan', 'TM', 'TKM', '+993'],
        ['Tuvalu', 'TV', 'TUV', '+688'],
        ['Uganda', 'UG', 'UGA', '+256'],
        ['Ukraine', 'UA', 'UKR', '+380'],
        ['United Arab Emirates', 'AE', 'ARE', '+971'],
        ['United Kingdom', 'GB', 'GBR', '+44'],
        ['United States', 'US', 'USA', '+1'],
        ['Uruguay', 'UY', 'URY', '+598'],
        ['Uzbekistan', 'UZ', 'UZB', '+998'],
        ['Vanuatu', 'VU', 'VUT', '+678'],
        ['Vatican City', 'VA', 'VAT', '+379'],
        ['Venezuela', 'VE', 'VEN', '+58'],
        ['Vietnam', 'VN', 'VNM', '+84'],
        ['Yemen', 'YE', 'YEM', '+967'],
        ['Zambia', 'ZM', 'ZMB', '+260'],
        ['Zimbabwe', 'ZW', 'ZWE', '+263'],
    ];

    private const LOCALIZATION = [
        'IN' => ['INR', 'en', 'Asia/Kolkata', 'support-in@sirieducation.com', '+91 00000 00000', 'd/m/Y', 'H:i', '1,23,456.78'],
        'US' => ['USD', 'en', 'America/New_York', 'support-us@sirieducation.com', '+1 000 000 0000', 'm/d/Y', 'h:i A', '1,234.56'],
        'GB' => ['GBP', 'en', 'Europe/London', 'support-uk@sirieducation.com', '+44 0000 000000', 'd/m/Y', 'H:i', '1,234.56'],
        'CA' => ['CAD', 'en', 'America/Toronto', 'support-ca@sirieducation.com', '+1 000 000 0000', 'Y-m-d', 'H:i', '1,234.56'],
        'AU' => ['AUD', 'en', 'Australia/Sydney', 'support-au@sirieducation.com', '+61 000 000 000', 'd/m/Y', 'h:i A', '1,234.56'],
    ];

    public function run(): void
    {
        $currencyIds = Currency::query()->pluck('id', 'code');
        $languageIds = Language::query()->pluck('id', 'code');

        foreach (self::COUNTRIES as $sortOrder => [$name, $iso2, $iso3, $phoneCode]) {
            $localization = self::LOCALIZATION[$iso2] ?? null;

            Country::updateOrCreate(
                ['iso2' => $iso2],
                array_filter([
                    'name' => $name,
                    'iso3' => $iso3,
                    'phone_code' => $phoneCode,
                    'flag' => $this->flagEmoji($iso2),
                    'sort_order' => $sortOrder,
                    'status' => 'active',
                    'default_currency_id' => $localization ? ($currencyIds[$localization[0]] ?? null) : null,
                    'default_language_id' => $localization ? ($languageIds[$localization[1]] ?? null) : null,
                    'default_timezone' => $localization[2] ?? null,
                    'support_email' => $localization[3] ?? null,
                    'support_phone' => $localization[4] ?? null,
                    'date_format' => $localization[5] ?? null,
                    'time_format' => $localization[6] ?? null,
                    'number_format' => $localization[7] ?? null,
                ], fn($value): bool => $value !== null)
            );
        }
    }

    /** Convert an ISO 3166-1 alpha-2 code into its flag emoji via regional indicator symbols. */
    private function flagEmoji(string $iso2): string
    {
        $codePoints = array_map(
            fn(string $letter): int => 0x1F1E6 + (ord($letter) - ord('A')),
            str_split(strtoupper($iso2))
        );

        return implode('', array_map('mb_chr', $codePoints));
    }
}
