<?php

declare(strict_types=1);

namespace App\Reporting\Registry;

use App\Reporting\Contracts\MetricRegistryInterface;
use App\Reporting\DTOs\MetricDefinition;
use App\Reporting\Enums\MetricUnit;
use App\Reporting\Enums\ReportDataFreshness;
use App\Reporting\Enums\ZeroDenominatorPolicy;
use App\Reporting\Exceptions\DuplicateMetricKeyException;
use App\Reporting\Services\BookingLessonMeetingOperationsReportService;
use App\Reporting\Support\UniqueDefinitionKeys;

/**
 * The Version 1 metric catalogue (Phase 18B §11 / Phase 18C §15) —
 * metadata only, so two dashboards can never define the same named
 * KPI two different ways. Every metric here is now backed by a real
 * query in {@see BookingLessonMeetingOperationsReportService}
 * (`calculationOwner` names it) except `single_paid_bookings`/
 * `daily_recurring_bookings`/`weekly_recurring_bookings`, which became
 * calculable this phase via the new `bookings.recurrence_frequency`
 * column (Phase 18C data-provenance decision, Outcome B) — no metric
 * here is left `available`-adjacent while its calculation owner still
 * says GAP.
 *
 * `bookings_rescheduled` is new this phase (Outcome A, §6.2):
 * `booking_activities.action` is a structured, enum-typed column
 * (never free-text audit parsing) that already records every
 * `rescheduled` lifecycle event — no migration was needed for the
 * count itself, only a supporting index.
 */
final class MetricRegistry implements MetricRegistryInterface
{
    /** @var array<string, MetricDefinition> */
    private array $definitions;

    public function __construct()
    {
        $this->definitions = $this->buildDefinitions();
    }

    public function all(): array
    {
        return array_values($this->definitions);
    }

    public function find(string $key): ?MetricDefinition
    {
        return $this->definitions[$key] ?? null;
    }

    /** @return array<string, MetricDefinition> */
    private function buildDefinitions(): array
    {
        return UniqueDefinitionKeys::index(
            $this->definitionList(),
            fn (MetricDefinition $definition): string => $definition->key,
            fn (string $key) => throw DuplicateMetricKeyException::forKey($key),
        );
    }

    /** @return list<MetricDefinition> */
    private function definitionList(): array
    {
        return [
            new MetricDefinition(
                key: 'bookings_scheduled',
                label: 'Bookings scheduled',
                description: 'Every booking created in the period, regardless of eventual outcome.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor', 'booking_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->total (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'demo_bookings',
                label: 'Demo bookings',
                description: 'Bookings of the approved Version 1 "free_demo" booking type.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['free_demo'],
                excludedStatuses: ['paid_one_to_one'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byType[free_demo] (Phase 18C). BookingAnalyticsService\'s "demo requests/bookers" remains a separate, distinct KPI (conversion-funnel framing) — not duplicated, not replaced.',
            ),
            new MetricDefinition(
                key: 'paid_bookings',
                label: 'Paid bookings',
                description: 'Bookings of the approved Version 1 "paid_one_to_one" booking type.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one'],
                excludedStatuses: ['free_demo'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byType[paid_one_to_one] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'single_paid_bookings',
                label: 'Single paid bookings',
                description: 'Paid bookings that are not part of a recurring series (recurrence_frequency is null and no historical recurring_group marker).',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[single] (Phase 18C). Resolved via the new `bookings.recurrence_frequency` column (data-provenance Outcome B) — see RecurrenceClassifier. A booking created before this column existed that WAS part of a recurring series (detected via the pre-existing `meta->recurring_group` JSON key) is bucketed `unknown_historical`, never folded into this count.',
            ),
            new MetricDefinition(
                key: 'daily_recurring_bookings',
                label: 'Daily recurring bookings',
                description: 'Paid bookings belonging to a daily recurrence series.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one', 'daily'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[daily] (Phase 18C). Only bookings created after the recurrence_frequency column existed can be classified daily/weekly — historical rows fall into `unknown_historical` (see single_paid_bookings).',
            ),
            new MetricDefinition(
                key: 'weekly_recurring_bookings',
                label: 'Weekly recurring bookings',
                description: 'Paid bookings belonging to a weekly recurrence series.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one', 'weekly'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[weekly] (Phase 18C). Same historical caveat as daily_recurring_bookings.',
            ),
            new MetricDefinition(
                key: 'bookings_rescheduled',
                label: 'Bookings rescheduled',
                description: 'Count of reschedule lifecycle events recorded in the period (a single booking rescheduled twice counts twice).',
                sourceDomain: 'Booking (booking_activities)',
                timestampField: 'created_at (of the activity row, not the booking)',
                includedStatuses: ['rescheduled'],
                excludedStatuses: ['requested', 'confirmed', 'cancelled', 'completed', 'no_show', 'guest_invited', 'guest_responded', 'payment_status_changed', 'meeting_linked'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['instructor', 'country', 'booking_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->rescheduled (Phase 18C). Data-provenance Outcome A (§6.2) — `booking_activities.action = \'rescheduled\'` is a structured, enum-typed, pre-existing column; no audit-message text parsing, no new schema concept, only a supporting index was added.',
            ),
            new MetricDefinition(
                key: 'lessons_completed',
                label: 'Lessons completed',
                description: 'Lessons whose finalized outcome is Completed.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['completed'],
                excludedStatuses: ['pending', 'student_no_show', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[completed] (Phase 18C). Authoritative source: `LessonOutcome::Completed` — never `LessonStatus::Completed` alone, which precedes finalization.',
            ),
            new MetricDefinition(
                key: 'lessons_scheduled',
                label: 'Lessons scheduled',
                description: 'Lessons whose scheduled start falls in the period, regardless of outcome yet (scheduled-activity view).',
                sourceDomain: 'Lessons',
                timestampField: 'starts_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->scheduled (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'student_no_shows',
                label: 'Student no-shows',
                description: 'Lessons whose finalized outcome is Student No-Show.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['student_no_show'],
                excludedStatuses: ['completed', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[student_no_show] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'instructor_no_shows',
                label: 'Instructor no-shows',
                description: 'Lessons whose finalized outcome is Instructor No-Show.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['instructor_no_show'],
                excludedStatuses: ['completed', 'student_no_show', 'both_absent', 'technical_issue', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[instructor_no_show] (Phase 18C). Also feeds `App\Quality`\'s existing InstructorNoShow/RepeatedInstructorNoShows detectors — reused, never recomputed independently.',
            ),
            new MetricDefinition(
                key: 'technical_issue_lessons',
                label: 'Technical-issue lessons',
                description: 'Lessons whose finalized outcome is Technical Issue.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['technical_issue'],
                excludedStatuses: ['completed', 'student_no_show', 'instructor_no_show', 'both_absent', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[technical_issue] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'disputed_lessons',
                label: 'Disputed lessons',
                description: 'Lessons currently under active dispute (LessonStatus::Disputed) — a snapshot of right now, not period-scoped; disputes can reopen any no-show/technical-issue decision, so this is distinct from technical_issue_lessons.',
                sourceDomain: 'Lessons',
                timestampField: 'n/a (current-state snapshot, like a Quality alert queue)',
                includedStatuses: ['disputed'],
                excludedStatuses: ['scheduled', 'live', 'completed', 'student_no_show', 'instructor_no_show', 'both_no_show', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped — always "as of now".',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->disputed (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'unfinalized_past_due_lessons',
                label: 'Unfinalized, past-due lessons',
                description: 'Lessons scheduled in the period whose end time has passed without a finalized outcome — an operational "stuck" indicator.',
                sourceDomain: 'Lessons',
                timestampField: 'starts_at (scoping) / ends_at (past-due test)',
                includedStatuses: ['pending'],
                excludedStatuses: ['completed', 'student_no_show', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone for period scoping; 'past-due' itself compares against the server clock.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->unfinalizedPastDue (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'cancelled_bookings',
                label: 'Cancelled bookings',
                description: 'Bookings cancelled in the period.',
                sourceDomain: 'Booking',
                timestampField: 'created_at (booking-created-in-period business-event view — status breakdown, not cancelled_at)',
                includedStatuses: ['cancelled'],
                excludedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byStatus[cancelled] (Phase 18C). BookingAnalyticsService\'s own "cancelled/cancellation rate" figure remains a separate, distinct KPI (conversion-funnel framing) — not duplicated, not replaced.',
            ),
            new MetricDefinition(
                key: 'meeting_creation_failures',
                label: 'Meeting creation failures',
                description: 'Meetings whose creation failed (booking_meetings.status = Failed).',
                sourceDomain: 'Booking (Meetings)',
                timestampField: 'booking_meetings.created_at',
                includedStatuses: ['failed'],
                excludedStatuses: ['pending', 'created', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->failed (Phase 18C). Authoritative source corrected from the Phase 18B note: `bookings.meeting_status` no longer exists (dropped by migration 2026_07_19_100000) — the live authoritative column is `booking_meetings.status`, same `MeetingStatus::Failed` case.',
            ),
            new MetricDefinition(
                key: 'meetings_missing',
                label: 'Confirmed bookings missing a meeting',
                description: 'Confirmed bookings whose scheduled start falls in the period with no successfully-created meeting.',
                sourceDomain: 'Booking (Meetings)',
                timestampField: 'bookings.starts_at',
                includedStatuses: ['confirmed'],
                excludedStatuses: ['pending', 'cancelled', 'completed', 'no_show'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->missingMeeting (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'student_joined_meetings',
                label: 'Student joined',
                description: 'Lessons in the period with at least one recorded student join event. A missing timestamp is "no evidence yet", never counted as absence.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping) / student_first_joined_at (evidence)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->studentJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'instructor_joined_meetings',
                label: 'Instructor joined',
                description: 'Lessons in the period with at least one recorded instructor join event.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping) / instructor_first_joined_at (evidence)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->instructorJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'both_joined_meetings',
                label: 'Both participants joined',
                description: 'Lessons in the period with recorded join evidence for both student and instructor.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->bothJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'meeting_technical_issue_reports',
                label: 'Technical issue reports',
                description: 'Technical issue reports submitted in the period — a report count, not a distinct-affected-lesson count (one lesson may have more than one report).',
                sourceDomain: 'Lessons (lesson_technical_issue_reports)',
                timestampField: 'submitted_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor', 'student', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->technicalIssueReports (Phase 18C).',
            ),
            // ── Phase 18D — Student Engagement ────────────────────────────
            new MetricDefinition(
                key: 'total_students',
                label: 'Total students',
                description: 'Users holding the student role — the single authoritative membership definition, current state.',
                sourceDomain: 'Users',
                timestampField: 'n/a (current-state count)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country', 'education_level', 'student_status'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->totalStudents (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'new_students_in_period',
                label: 'New students',
                description: 'Student-role accounts created in the period.',
                sourceDomain: 'Users',
                timestampField: 'users.created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->newInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'verified_students',
                label: 'Verified students',
                description: 'Student-role accounts with a verified email (email_verified_at set).',
                sourceDomain: 'Users',
                timestampField: 'users.email_verified_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Total is current-state; 'verified in period' uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->verifiedTotal / verifiedInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'engaged_students_in_period',
                label: 'Engaged students in period',
                description: 'Reporting definition (§6.1 Outcome B), NOT an account status: students with ≥1 booking created OR ≥1 lesson finalized Completed in the period. Deliberately named distinctly from the student_status account attribute.',
                sourceDomain: 'Users, Booking, Lessons',
                timestampField: 'bookings.created_at / lessons.outcome_finalized_at',
                includedStatuses: ['completed (lesson outcome leg)'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->engagedInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'students_without_recent_learning_activity',
                label: 'Students without recent learning activity',
                description: 'Deterministic inactivity rule (§6.2/6.3): non-suspended, non-archived student accounts with zero bookings created and zero lessons finalized in the period. Never a predictive risk score.',
                sourceDomain: 'Users, Booking, Lessons',
                timestampField: 'bookings.created_at / lessons.outcome_finalized_at (absence within period)',
                includedStatuses: ['registered', 'active'],
                excludedStatuses: ['suspended', 'archived'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->withoutRecentLearningActivity (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'students_with_active_learning_plans',
                label: 'Students with active learning plans',
                description: 'Students with ≥1 learning plan currently in the Active status (current-state).',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['active'],
                excludedStatuses: ['draft', 'awaiting_assessment', 'paused', 'review_due', 'completed', 'archived'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->withActiveLearningPlans (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'student_recurring_participation',
                label: 'Student recurring participation',
                description: 'Distinct students per recurrence bucket for bookings created in the period. unknown_historical (pre-provenance recurring rows) is never folded into single.',
                sourceDomain: 'Booking',
                timestampField: 'bookings.created_at',
                includedStatuses: ['single', 'daily', 'weekly', 'unknown_historical'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->recurringParticipation via RecurrenceClassifier (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'student_lifetime_booking_buckets',
                label: 'Student lifetime booking distribution',
                description: 'Distribution of students by lifetime booking count (0 / 1 / 2-5 / 6-10 / 11+). A plain activity distribution — never labeled retention (§6.4 Outcome C: no authoritative retention definition exists).',
                sourceDomain: 'Users, Booking',
                timestampField: 'n/a (lifetime, not period-scoped)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->lifetimeBookingBuckets (Phase 18D).',
            ),
            // ── Phase 18D — Instructor Performance ────────────────────────
            new MetricDefinition(
                key: 'instructors_by_lifecycle_status',
                label: 'Instructors by lifecycle status',
                description: 'Current user_profiles.instructor_status distribution — all 11 lifecycle cases reported distinctly, none collapsed.',
                sourceDomain: 'Users (user_profiles)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['draft', 'submitted', 'under_review', 'documents_pending', 'interview_required', 'approved', 'active', 'vacation', 'suspended', 'archived', 'rejected'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceReportService::lifecycleSummary()->byStatus (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'instructor_approvals_in_period',
                label: 'Instructor approvals',
                description: 'Distinct instructors approved in the period, counted from the structured activity_log event application_approved (log name instructor) — never instructor_reviewed_at, which is overwritten by every later admin transition.',
                sourceDomain: 'Activity Log (structured event key)',
                timestampField: 'activity_log.created_at',
                includedStatuses: ['application_approved'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::approvalsInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'unique_students_taught',
                label: 'Unique students taught',
                description: 'Distinct students with a non-cancelled booking created in the period.',
                sourceDomain: 'Booking',
                timestampField: 'bookings.created_at',
                includedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                excludedStatuses: ['cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor', 'country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceReportService::activitySummary()->uniqueStudents (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'repeat_paid_students',
                label: 'Repeat paid students',
                description: 'Distinct students with ≥2 LIFETIME non-cancelled paid-type bookings with the same instructor. An activity proxy — never labeled retention (§6.7: no same-instructor retention definition with a complete observation window exists).',
                sourceDomain: 'Booking',
                timestampField: 'n/a (lifetime, not period-scoped)',
                includedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                excludedStatuses: ['cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::repeatPaidStudents (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'booked_teaching_hours',
                label: 'Booked teaching hours',
                description: 'Sum of scheduled durations for Confirmed/Completed bookings whose scheduled start falls in the period. Fully source-backed (§6.5).',
                sourceDomain: 'Booking',
                timestampField: 'bookings.starts_at',
                includedStatuses: ['confirmed', 'completed'],
                excludedStatuses: ['pending', 'cancelled', 'no_show'],
                unit: MetricUnit::Duration,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::bookedTeachingHours (Phase 18D). Integer minutes internally, hours for display.',
            ),
            new MetricDefinition(
                key: 'published_weekly_availability_hours',
                label: 'Published weekly availability (current)',
                description: 'CURRENT-STATE weekly schedule hours from active teacher_availability windows. §6.5 Outcome C: historical availability is not reconstructable (schedule rows are updated in place, no versioning), so NO utilization rate is derived from this — it is displayed as a separate, clearly current-state figure only.',
                sourceDomain: 'Availability (teacher_availability)',
                timestampField: 'n/a (current-state configuration)',
                includedStatuses: ['is_active = true'],
                excludedStatuses: [],
                unit: MetricUnit::Duration,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: 'Current-state configuration; not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::publishedWeeklyAvailabilityHours (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'demo_to_paid_conversion',
                label: 'Demo-to-paid conversion',
                description: 'Reuses the platform\'s EXISTING authoritative definition verbatim (§6.6 Outcome A — BookingAnalyticsRepository::conversion(), tested): distinct demo-booking students in period (any status), converted when ANY paid-type booking is created at or after the demo (any instructor/subject, unbounded window, once per student). Because the definition carries no instructor/subject/country attribution, per-instructor/subject/country conversion is UNAVAILABLE, not invented.',
                sourceDomain: 'Booking (BookingAnalyticsRepository — existing calculation owner)',
                timestampField: 'bookings.created_at (demo leg period-scoped; paid leg unbounded)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Percentage,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone for the demo leg.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingAnalyticsRepository::conversion(), surfaced by InstructorPerformanceReportService::demoConversion (Phase 18D). Rate is null — never 0% — with zero demo bookers.',
            ),
        ];
    }
}
