<?php

declare(strict_types=1);

namespace App\Reporting\Registry;

use App\Reporting\Contracts\MetricRegistryInterface;
use App\Reporting\DTOs\MetricDefinition;
use App\Reporting\Enums\MetricUnit;
use App\Reporting\Enums\ReportDataFreshness;
use App\Reporting\Enums\ZeroDenominatorPolicy;
use App\Reporting\Exceptions\DuplicateMetricKeyException;
use App\Reporting\Services\BookingLessonMeetingOperationsReportService;
use App\Reporting\Support\UniqueDefinitionKeys;

/**
 * The Version 1 metric catalogue (Phase 18B §11 / Phase 18C §15) —
 * metadata only, so two dashboards can never define the same named
 * KPI two different ways. Every metric here is now backed by a real
 * query in {@see BookingLessonMeetingOperationsReportService}
 * (`calculationOwner` names it) except `single_paid_bookings`/
 * `daily_recurring_bookings`/`weekly_recurring_bookings`, which became
 * calculable this phase via the new `bookings.recurrence_frequency`
 * column (Phase 18C data-provenance decision, Outcome B) — no metric
 * here is left `available`-adjacent while its calculation owner still
 * says GAP.
 *
 * `bookings_rescheduled` is new this phase (Outcome A, §6.2):
 * `booking_activities.action` is a structured, enum-typed column
 * (never free-text audit parsing) that already records every
 * `rescheduled` lifecycle event — no migration was needed for the
 * count itself, only a supporting index.
 */
final class MetricRegistry implements MetricRegistryInterface
{
    /** @var array<string, MetricDefinition> */
    private array $definitions;

    public function __construct()
    {
        $this->definitions = $this->buildDefinitions();
    }

    public function all(): array
    {
        return array_values($this->definitions);
    }

    public function find(string $key): ?MetricDefinition
    {
        return $this->definitions[$key] ?? null;
    }

    /** @return array<string, MetricDefinition> */
    private function buildDefinitions(): array
    {
        return UniqueDefinitionKeys::index(
            $this->definitionList(),
            fn (MetricDefinition $definition): string => $definition->key,
            fn (string $key) => throw DuplicateMetricKeyException::forKey($key),
        );
    }

    /** @return list<MetricDefinition> */
    private function definitionList(): array
    {
        return [
            new MetricDefinition(
                key: 'bookings_scheduled',
                label: 'Bookings scheduled',
                description: 'Every booking created in the period, regardless of eventual outcome.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor', 'booking_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->total (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'demo_bookings',
                label: 'Demo bookings',
                description: 'Bookings of the approved Version 1 "free_demo" booking type.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['free_demo'],
                excludedStatuses: ['paid_one_to_one'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byType[free_demo] (Phase 18C). BookingAnalyticsService\'s "demo requests/bookers" remains a separate, distinct KPI (conversion-funnel framing) — not duplicated, not replaced.',
            ),
            new MetricDefinition(
                key: 'paid_bookings',
                label: 'Paid bookings',
                description: 'Bookings of the approved Version 1 "paid_one_to_one" booking type.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one'],
                excludedStatuses: ['free_demo'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byType[paid_one_to_one] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'single_paid_bookings',
                label: 'Single paid bookings',
                description: 'Paid bookings that are not part of a recurring series (recurrence_frequency is null and no historical recurring_group marker).',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[single] (Phase 18C). Resolved via the new `bookings.recurrence_frequency` column (data-provenance Outcome B) — see RecurrenceClassifier. A booking created before this column existed that WAS part of a recurring series (detected via the pre-existing `meta->recurring_group` JSON key) is bucketed `unknown_historical`, never folded into this count.',
            ),
            new MetricDefinition(
                key: 'daily_recurring_bookings',
                label: 'Daily recurring bookings',
                description: 'Paid bookings belonging to a daily recurrence series.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one', 'daily'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[daily] (Phase 18C). Only bookings created after the recurrence_frequency column existed can be classified daily/weekly — historical rows fall into `unknown_historical` (see single_paid_bookings).',
            ),
            new MetricDefinition(
                key: 'weekly_recurring_bookings',
                label: 'Weekly recurring bookings',
                description: 'Paid bookings belonging to a weekly recurrence series.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one', 'weekly'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[weekly] (Phase 18C). Same historical caveat as daily_recurring_bookings.',
            ),
            new MetricDefinition(
                key: 'bookings_rescheduled',
                label: 'Bookings rescheduled',
                description: 'Count of reschedule lifecycle events recorded in the period (a single booking rescheduled twice counts twice).',
                sourceDomain: 'Booking (booking_activities)',
                timestampField: 'created_at (of the activity row, not the booking)',
                includedStatuses: ['rescheduled'],
                excludedStatuses: ['requested', 'confirmed', 'cancelled', 'completed', 'no_show', 'guest_invited', 'guest_responded', 'payment_status_changed', 'meeting_linked'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['instructor', 'country', 'booking_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->rescheduled (Phase 18C). Data-provenance Outcome A (§6.2) — `booking_activities.action = \'rescheduled\'` is a structured, enum-typed, pre-existing column; no audit-message text parsing, no new schema concept, only a supporting index was added.',
            ),
            new MetricDefinition(
                key: 'lessons_completed',
                label: 'Lessons completed',
                description: 'Lessons whose finalized outcome is Completed.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['completed'],
                excludedStatuses: ['pending', 'student_no_show', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[completed] (Phase 18C). Authoritative source: `LessonOutcome::Completed` — never `LessonStatus::Completed` alone, which precedes finalization.',
            ),
            new MetricDefinition(
                key: 'lessons_scheduled',
                label: 'Lessons scheduled',
                description: 'Lessons whose scheduled start falls in the period, regardless of outcome yet (scheduled-activity view).',
                sourceDomain: 'Lessons',
                timestampField: 'starts_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->scheduled (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'student_no_shows',
                label: 'Student no-shows',
                description: 'Lessons whose finalized outcome is Student No-Show.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['student_no_show'],
                excludedStatuses: ['completed', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[student_no_show] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'instructor_no_shows',
                label: 'Instructor no-shows',
                description: 'Lessons whose finalized outcome is Instructor No-Show.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['instructor_no_show'],
                excludedStatuses: ['completed', 'student_no_show', 'both_absent', 'technical_issue', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[instructor_no_show] (Phase 18C). Also feeds `App\Quality`\'s existing InstructorNoShow/RepeatedInstructorNoShows detectors — reused, never recomputed independently.',
            ),
            new MetricDefinition(
                key: 'technical_issue_lessons',
                label: 'Technical-issue lessons',
                description: 'Lessons whose finalized outcome is Technical Issue.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['technical_issue'],
                excludedStatuses: ['completed', 'student_no_show', 'instructor_no_show', 'both_absent', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[technical_issue] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'disputed_lessons',
                label: 'Disputed lessons',
                description: 'Lessons currently under active dispute (LessonStatus::Disputed) — a snapshot of right now, not period-scoped; disputes can reopen any no-show/technical-issue decision, so this is distinct from technical_issue_lessons.',
                sourceDomain: 'Lessons',
                timestampField: 'n/a (current-state snapshot, like a Quality alert queue)',
                includedStatuses: ['disputed'],
                excludedStatuses: ['scheduled', 'live', 'completed', 'student_no_show', 'instructor_no_show', 'both_no_show', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped — always "as of now".',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->disputed (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'unfinalized_past_due_lessons',
                label: 'Unfinalized, past-due lessons',
                description: 'Lessons scheduled in the period whose end time has passed without a finalized outcome — an operational "stuck" indicator.',
                sourceDomain: 'Lessons',
                timestampField: 'starts_at (scoping) / ends_at (past-due test)',
                includedStatuses: ['pending'],
                excludedStatuses: ['completed', 'student_no_show', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone for period scoping; 'past-due' itself compares against the server clock.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->unfinalizedPastDue (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'cancelled_bookings',
                label: 'Cancelled bookings',
                description: 'Bookings cancelled in the period.',
                sourceDomain: 'Booking',
                timestampField: 'created_at (booking-created-in-period business-event view — status breakdown, not cancelled_at)',
                includedStatuses: ['cancelled'],
                excludedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byStatus[cancelled] (Phase 18C). BookingAnalyticsService\'s own "cancelled/cancellation rate" figure remains a separate, distinct KPI (conversion-funnel framing) — not duplicated, not replaced.',
            ),
            new MetricDefinition(
                key: 'meeting_creation_failures',
                label: 'Meeting creation failures',
                description: 'Meetings whose creation failed (booking_meetings.status = Failed).',
                sourceDomain: 'Booking (Meetings)',
                timestampField: 'booking_meetings.created_at',
                includedStatuses: ['failed'],
                excludedStatuses: ['pending', 'created', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->failed (Phase 18C). Authoritative source corrected from the Phase 18B note: `bookings.meeting_status` no longer exists (dropped by migration 2026_07_19_100000) — the live authoritative column is `booking_meetings.status`, same `MeetingStatus::Failed` case.',
            ),
            new MetricDefinition(
                key: 'meetings_missing',
                label: 'Confirmed bookings missing a meeting',
                description: 'Confirmed bookings whose scheduled start falls in the period with no successfully-created meeting.',
                sourceDomain: 'Booking (Meetings)',
                timestampField: 'bookings.starts_at',
                includedStatuses: ['confirmed'],
                excludedStatuses: ['pending', 'cancelled', 'completed', 'no_show'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->missingMeeting (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'student_joined_meetings',
                label: 'Student joined',
                description: 'Lessons in the period with at least one recorded student join event. A missing timestamp is "no evidence yet", never counted as absence.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping) / student_first_joined_at (evidence)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->studentJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'instructor_joined_meetings',
                label: 'Instructor joined',
                description: 'Lessons in the period with at least one recorded instructor join event.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping) / instructor_first_joined_at (evidence)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->instructorJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'both_joined_meetings',
                label: 'Both participants joined',
                description: 'Lessons in the period with recorded join evidence for both student and instructor.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->bothJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'meeting_technical_issue_reports',
                label: 'Technical issue reports',
                description: 'Technical issue reports submitted in the period — a report count, not a distinct-affected-lesson count (one lesson may have more than one report).',
                sourceDomain: 'Lessons (lesson_technical_issue_reports)',
                timestampField: 'submitted_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor', 'student', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->technicalIssueReports (Phase 18C).',
            ),
            // ── Phase 18D — Student Engagement ────────────────────────────
            new MetricDefinition(
                key: 'total_students',
                label: 'Total students',
                description: 'Users holding the student role — the single authoritative membership definition, current state.',
                sourceDomain: 'Users',
                timestampField: 'n/a (current-state count)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country', 'education_level', 'student_status'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->totalStudents (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'new_students_in_period',
                label: 'New students',
                description: 'Student-role accounts created in the period.',
                sourceDomain: 'Users',
                timestampField: 'users.created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->newInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'verified_students',
                label: 'Verified students',
                description: 'Student-role accounts with a verified email (email_verified_at set).',
                sourceDomain: 'Users',
                timestampField: 'users.email_verified_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Total is current-state; 'verified in period' uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->verifiedTotal / verifiedInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'engaged_students_in_period',
                label: 'Engaged students in period',
                description: 'Reporting definition (§6.1 Outcome B), NOT an account status: students with ≥1 booking created OR ≥1 lesson finalized Completed in the period. Deliberately named distinctly from the student_status account attribute.',
                sourceDomain: 'Users, Booking, Lessons',
                timestampField: 'bookings.created_at / lessons.outcome_finalized_at',
                includedStatuses: ['completed (lesson outcome leg)'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->engagedInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'students_without_recent_learning_activity',
                label: 'Students without recent learning activity',
                description: 'Deterministic inactivity rule (§6.2/6.3): non-suspended, non-archived student accounts with zero bookings created and zero lessons finalized in the period. Never a predictive risk score.',
                sourceDomain: 'Users, Booking, Lessons',
                timestampField: 'bookings.created_at / lessons.outcome_finalized_at (absence within period)',
                includedStatuses: ['registered', 'active'],
                excludedStatuses: ['suspended', 'archived'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->withoutRecentLearningActivity (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'students_with_active_learning_plans',
                label: 'Students with active learning plans',
                description: 'Students with ≥1 learning plan currently in the Active status (current-state).',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['active'],
                excludedStatuses: ['draft', 'awaiting_assessment', 'paused', 'review_due', 'completed', 'archived'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->withActiveLearningPlans (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'student_recurring_participation',
                label: 'Student recurring participation',
                description: 'Distinct students per recurrence bucket for bookings created in the period. unknown_historical (pre-provenance recurring rows) is never folded into single.',
                sourceDomain: 'Booking',
                timestampField: 'bookings.created_at',
                includedStatuses: ['single', 'daily', 'weekly', 'unknown_historical'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->recurringParticipation via RecurrenceClassifier (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'student_lifetime_booking_buckets',
                label: 'Student lifetime booking distribution',
                description: 'Distribution of students by lifetime booking count (0 / 1 / 2-5 / 6-10 / 11+). A plain activity distribution — never labeled retention (§6.4 Outcome C: no authoritative retention definition exists).',
                sourceDomain: 'Users, Booking',
                timestampField: 'n/a (lifetime, not period-scoped)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewStudentReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'StudentEngagementReportService::summary()->lifetimeBookingBuckets (Phase 18D).',
            ),
            // ── Phase 18D — Instructor Performance ────────────────────────
            new MetricDefinition(
                key: 'instructors_by_lifecycle_status',
                label: 'Instructors by lifecycle status',
                description: 'Current user_profiles.instructor_status distribution — all 11 lifecycle cases reported distinctly, none collapsed.',
                sourceDomain: 'Users (user_profiles)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['draft', 'submitted', 'under_review', 'documents_pending', 'interview_required', 'approved', 'active', 'vacation', 'suspended', 'archived', 'rejected'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceReportService::lifecycleSummary()->byStatus (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'instructor_approvals_in_period',
                label: 'Instructor approvals',
                description: 'Distinct instructors approved in the period, counted from the structured activity_log event application_approved (log name instructor) — never instructor_reviewed_at, which is overwritten by every later admin transition.',
                sourceDomain: 'Activity Log (structured event key)',
                timestampField: 'activity_log.created_at',
                includedStatuses: ['application_approved'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::approvalsInPeriod (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'unique_students_taught',
                label: 'Unique students taught',
                description: 'Distinct students with a non-cancelled booking created in the period.',
                sourceDomain: 'Booking',
                timestampField: 'bookings.created_at',
                includedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                excludedStatuses: ['cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor', 'country'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceReportService::activitySummary()->uniqueStudents (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'repeat_paid_students',
                label: 'Repeat paid students',
                description: 'Distinct students with ≥2 LIFETIME non-cancelled paid-type bookings with the same instructor. An activity proxy — never labeled retention (§6.7: no same-instructor retention definition with a complete observation window exists).',
                sourceDomain: 'Booking',
                timestampField: 'n/a (lifetime, not period-scoped)',
                includedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                excludedStatuses: ['cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::repeatPaidStudents (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'booked_teaching_hours',
                label: 'Booked teaching hours',
                description: 'Sum of scheduled durations for Confirmed/Completed bookings whose scheduled start falls in the period. Fully source-backed (§6.5).',
                sourceDomain: 'Booking',
                timestampField: 'bookings.starts_at',
                includedStatuses: ['confirmed', 'completed'],
                excludedStatuses: ['pending', 'cancelled', 'no_show'],
                unit: MetricUnit::Duration,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::bookedTeachingHours (Phase 18D). Integer minutes internally, hours for display.',
            ),
            new MetricDefinition(
                key: 'published_weekly_availability_hours',
                label: 'Published weekly availability (current)',
                description: 'CURRENT-STATE weekly schedule hours from active teacher_availability windows. §6.5 Outcome C: historical availability is not reconstructable (schedule rows are updated in place, no versioning), so NO utilization rate is derived from this — it is displayed as a separate, clearly current-state figure only.',
                sourceDomain: 'Availability (teacher_availability)',
                timestampField: 'n/a (current-state configuration)',
                includedStatuses: ['is_active = true'],
                excludedStatuses: [],
                unit: MetricUnit::Duration,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: 'Current-state configuration; not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorPerformanceRepository::publishedWeeklyAvailabilityHours (Phase 18D).',
            ),
            new MetricDefinition(
                key: 'demo_to_paid_conversion',
                label: 'Demo-to-paid conversion',
                description: 'Reuses the platform\'s EXISTING authoritative definition verbatim (§6.6 Outcome A — BookingAnalyticsRepository::conversion(), tested): distinct demo-booking students in period (any status), converted when ANY paid-type booking is created at or after the demo (any instructor/subject, unbounded window, once per student). Because the definition carries no instructor/subject/country attribution, per-instructor/subject/country conversion is UNAVAILABLE, not invented.',
                sourceDomain: 'Booking (BookingAnalyticsRepository — existing calculation owner)',
                timestampField: 'bookings.created_at (demo leg period-scoped; paid leg unbounded)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Percentage,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewInstructorReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone for the demo leg.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingAnalyticsRepository::conversion(), surfaced by InstructorPerformanceReportService::demoConversion (Phase 18D). Rate is null — never 0% — with zero demo bookers.',
            ),
            // ── Phase 18E — Financial reporting ───────────────────────────
            new MetricDefinition(
                key: 'successful_payment_collections',
                label: 'Successful external collections',
                description: 'Money actually captured through a payment provider: booking_payments attempts in Captured (or Refunded — captured before being refunded). The attempt-level provider ground truth, never the booking-level snapshot. Integer minor units, grouped by currency, never summed across currencies.',
                sourceDomain: 'Booking (booking_payments)',
                timestampField: 'created_at (attempt scoping); paid_at marks capture',
                includedStatuses: ['captured', 'refunded'],
                excludedStatuses: ['pending', 'authorized', 'processing', 'failed', 'cancelled', 'expired', 'unknown', 'resolution_required'],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewPaymentReports',
                supportedDimensions: ['currency', 'provider'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'FinancialReportsService::paymentSummary()->capturedAmountByCurrency (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'payment_success_rate',
                label: 'Payment success rate',
                description: 'Captured-at-some-point attempts ÷ TERMINAL attempts (captured/failed/cancelled/expired/refunded). In-flight attempts (pending/authorized/processing/unknown/resolution_required) are not yet outcomes and are excluded from the denominator.',
                sourceDomain: 'Booking (booking_payments)',
                timestampField: 'created_at',
                includedStatuses: ['captured', 'refunded'],
                excludedStatuses: ['pending', 'authorized', 'processing', 'unknown', 'resolution_required'],
                unit: MetricUnit::Percentage,
                sensitive: false,
                financial: true,
                requiredPermission: 'ViewPaymentReports',
                supportedDimensions: ['currency', 'provider'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'FinancialReportsService::paymentSummary()->successRate (Phase 18E). Null — never 0% — with no terminal attempts.',
            ),
            new MetricDefinition(
                key: 'gross_paid_booking_value',
                label: 'Gross paid-booking value',
                description: 'COMMERCIAL VALUE, deliberately never labeled revenue (§7 Outcome B — no revenue-recognition definition exists): SUM(bookings.price) where payment_status = paid, by booking created_at. Same semantics as the legacy Booking Reports figure but grouped by currency (the legacy figure sums across currencies; documented discrepancy, legacy page untouched). Never added to collections or wallet consumption (double-counting prohibition).',
                sourceDomain: 'Booking',
                timestampField: 'bookings.created_at',
                includedStatuses: ['paid'],
                excludedStatuses: ['not_required', 'pending', 'failed', 'refunded'],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewPaymentReports',
                supportedDimensions: ['currency', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'PaymentFinancialReportRepository::grossPaidBookingValueByCurrency (Phase 18E) — DECIMAL SQL sum converted per currency via MoneyFormatter::toMinor, never float.',
            ),
            new MetricDefinition(
                key: 'wallet_current_liability',
                label: 'Current wallet liability',
                description: 'AS-OF-NOW obligation: SUM(wallets.balance_minor) per currency over the guarded single-writer balances. Never period-scoped — the report-period filter does not change it. Historical liability is NOT implemented (§8: ledger reconstruction unproven against snapshots).',
                sourceDomain: 'Wallet (wallets)',
                timestampField: 'n/a (as-of-now, timestamp displayed)',
                includedStatuses: ['active', 'frozen', 'closed'],
                excludedStatuses: [],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewWalletReports',
                supportedDimensions: ['currency'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped; an as-of timestamp is displayed.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'WalletFinancialReportRepository::currentLiabilityByCurrency (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'wallet_ledger_movements',
                label: 'Wallet ledger movements',
                description: 'Period-event ledger aggregates grouped by (currency, entry type, direction). Recharge/refund/referral/promotional credits and admin adjustments remain distinct types; direction is per-row. A debit is wallet consumption — never external collection, never revenue. Posted and Reversed rows both included: a reversal writes an explicit offsetting Posted row, so gross activity and its reversal are each visible.',
                sourceDomain: 'Wallet (wallet_ledger_entries)',
                timestampField: 'created_at (status posted/reversed)',
                includedStatuses: ['posted', 'reversed'],
                excludedStatuses: ['pending', 'failed'],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewWalletReports',
                supportedDimensions: ['currency', 'wallet_transaction_type', 'student'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'WalletFinancialReportRepository::movements (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'wallet_balance_ledger_mismatches',
                label: 'Wallet balance/ledger mismatches',
                description: 'Wallets whose stored balance differs from their latest ledger balance_after_minor — a read-only reconciliation signal, never repaired from a report.',
                sourceDomain: 'Wallet',
                timestampField: 'n/a (as-of-now)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewWalletReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'WalletFinancialReportRepository::balanceMismatchCount (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'wallet_refunds_executed',
                label: 'Wallet refund credits executed',
                description: 'Refund-type wallet ledger credits in the period, grouped by currency (unlike currencies never summed). Version 1 lesson-refund policy is WALLET CREDIT ONLY — no gateway refund is inferred. Decision (disposition evaluated_at) and execution (ledger created_at / refund_executed_at) are distinct timestamps, never conflated.',
                sourceDomain: 'Wallet (refund ledger credits) + Earnings (lesson_financial_dispositions)',
                timestampField: 'wallet_ledger_entries.created_at (execution); lesson_financial_dispositions.evaluated_at (decision)',
                includedStatuses: ['posted', 'reversed'],
                excludedStatuses: ['pending', 'failed'],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewWalletReports',
                supportedDimensions: ['currency', 'lesson_outcome'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'WalletFinancialReportRepository::refundSummary (Phase 18E). Idempotency: the ledger unique idempotency_key ("lesson-refund:{disposition}:v{version}") makes duplicate execution attempts structurally uncountable twice.',
            ),
            new MetricDefinition(
                key: 'instructor_earnings_created',
                label: 'Instructor earnings created',
                description: 'Compensation obligations created in the period — earning_amount_minor from compensation agreements, NEVER the student-facing booking price. Amounts grouped by currency, never summed across currencies. Requires the strictest financial permission.',
                sourceDomain: 'Earnings (instructor_earnings)',
                timestampField: 'created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewInstructorCompensationReports',
                supportedDimensions: ['currency', 'instructor', 'earning_status'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorFinancialReportRepository::summary (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'instructor_earning_liability_by_status',
                label: 'Current earning liability by status',
                description: 'CURRENT-STATE amounts by current earning status (pending_hold/releasable/disputed_hold/settled/reversed/cancelled) per currency — "what does the platform owe right now, in which lifecycle bucket". Never period-scoped; period-created earnings are a separate metric.',
                sourceDomain: 'Earnings (instructor_earnings)',
                timestampField: 'n/a (current-state)',
                includedStatuses: ['pending_hold', 'releasable', 'settled', 'reversed', 'disputed_hold', 'cancelled'],
                excludedStatuses: [],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewInstructorCompensationReports',
                supportedDimensions: ['currency', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorFinancialReportRepository::earningLiabilityByStatusCurrency (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'settlement_allocation_integrity',
                label: 'Settlement allocation mismatches',
                description: 'Non-cancelled batches whose total_amount_minor differs from the sum of their allocated earnings. A settlement batch is an internal grouping, never an external transfer; a settled earning is not necessarily withdrawn.',
                sourceDomain: 'Earnings (instructor_settlement_batches + instructor_earnings.settlement_batch_id)',
                timestampField: 'n/a (as-of-now integrity check)',
                includedStatuses: ['draft', 'approved', 'processing', 'paid', 'failed'],
                excludedStatuses: ['cancelled'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewInstructorCompensationReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorFinancialReportRepository::settlementAllocationMismatchCount (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'withdrawals_by_status',
                label: 'Withdrawal requests by status',
                description: 'Withdrawal lifecycle counts by requested_at, plus requested amounts and paid net amounts (by paid_at), grouped by currency. An approved withdrawal is not a paid one; a created payout attempt is not a paid withdrawal; provider success is never inferred from a local processing state.',
                sourceDomain: 'Earnings (instructor_withdrawal_requests)',
                timestampField: 'requested_at (counts/requested amounts); paid_at (paid net amounts)',
                includedStatuses: ['submitted', 'under_review', 'approved', 'rejected', 'cancelled', 'processing', 'paid', 'failed', 'reversed'],
                excludedStatuses: [],
                unit: MetricUnit::MoneyMinor,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewInstructorCompensationReports',
                supportedDimensions: ['currency', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorFinancialReportRepository::summary (Phase 18E).',
            ),
            new MetricDefinition(
                key: 'payout_attempts_by_status',
                label: 'Payout attempts by status',
                description: 'External payout provider attempts (real or fake driver) by created_at, each lifecycle status distinct. Rendering this metric never triggers a payout, retry or provider request.',
                sourceDomain: 'Earnings (instructor_payout_attempts)',
                timestampField: 'created_at',
                includedStatuses: ['created', 'dispatching', 'submitted', 'acknowledged', 'processing', 'succeeded', 'failed', 'unknown', 'reversed', 'cancelled'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: true,
                requiredPermission: 'ViewInstructorCompensationReports',
                supportedDimensions: ['provider'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'InstructorFinancialReportRepository::summary (Phase 18E).',
            ),

            // ── Phase 18F — Learning Analytics ────────────────────────────
            new MetricDefinition(
                key: 'learning_goals_created',
                label: 'Learning goals created',
                description: 'Student learning goals created in the period (created_at). A goal is a student-defined objective — never counted as a Learning Plan.',
                sourceDomain: 'Learning Goals (student_learning_goals)',
                timestampField: 'created_at',
                includedStatuses: ['draft', 'active', 'paused', 'completed', 'archived'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::goalSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'learning_goals_completed',
                label: 'Learning goals completed',
                description: 'Goals whose authoritative completed_at falls in the period. Target-date elapse alone never completes a goal.',
                sourceDomain: 'Learning Goals (student_learning_goals)',
                timestampField: 'completed_at',
                includedStatuses: ['completed'],
                excludedStatuses: ['draft', 'active', 'paused', 'archived'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::goalSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'goals_without_plans',
                label: 'Goals not yet linked to a plan',
                description: 'CURRENT-STATE goals with no non-deleted Learning Plan referencing them. The SRS permits goals to precede plans — informational, never an error signal.',
                sourceDomain: 'Learning Goals (student_learning_goals ⟵ student_learning_plans.learning_goal_id)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['draft', 'active', 'paused', 'completed', 'archived'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::goalSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'learning_plans_created',
                label: 'Learning Plans created',
                description: 'Learning Plans created in the period (created_at), any lifecycle status. A recurring booking is never counted as a plan.',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'created_at',
                includedStatuses: ['draft', 'awaiting_assessment', 'active', 'paused', 'review_due', 'completed', 'archived'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::planSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'learning_plans_activated',
                label: 'Learning Plans activated',
                description: 'Plans whose authoritative started_at falls in the period — a PERIOD EVENT, distinct from the current-state Active count.',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'started_at',
                includedStatuses: ['active', 'paused', 'review_due', 'completed', 'archived'],
                excludedStatuses: ['draft', 'awaiting_assessment'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::planSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'learning_plans_completed',
                label: 'Learning Plans completed',
                description: 'Plans whose authoritative completed_at falls in the period. A plan reaching its target date is NOT automatically completed; archived is NOT completed. No completion rate exists (§7.2 — V1 has no proven cohort denominator).',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'completed_at',
                includedStatuses: ['completed'],
                excludedStatuses: ['archived'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::planSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'current_learning_plans_by_status',
                label: 'Current Learning Plans by status',
                description: 'CURRENT-STATE distribution over the full LearningPlanStatus lifecycle. Archived plans remain in historical counts forever.',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['draft', 'awaiting_assessment', 'active', 'paused', 'review_due', 'completed', 'archived'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::planSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'average_active_plan_progress',
                label: 'Average progress of active plans',
                description: 'Mean of the domain-maintained progress_percent across currently Active plans (§6.17-5: LearningPlanProgressCalculator averages each applicable evidence domain — milestones, directly-linked homework, plan-linked lessons, and the latest structured academic-review percentage — excluding domains with no applicable records; forces 100 on manual plan completion). Null when no plan is Active — never a fabricated 0%.',
                sourceDomain: 'Learning Plans (student_learning_plans.progress_percent)',
                timestampField: 'n/a (current-state average)',
                includedStatuses: ['active'],
                excludedStatuses: ['draft', 'awaiting_assessment', 'paused', 'review_due', 'completed', 'archived'],
                unit: MetricUnit::Percentage,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanProgressCalculator (source domain) surfaced by LearningPlanAnalyticsRepository::planSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'milestones_achieved',
                label: 'Milestones achieved',
                description: 'Plan-assigned milestones reaching Completed with completed_at in the period. Every milestone row is plan-assigned in this codebase — a definition can never be counted as an achievement. Skipped is never achieved.',
                sourceDomain: 'Learning Plans (learning_plan_milestones)',
                timestampField: 'completed_at',
                includedStatuses: ['completed'],
                excludedStatuses: ['pending', 'in_progress', 'skipped'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::milestoneReviewSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'progress_reviews_completed',
                label: 'Progress reviews completed',
                description: 'Structured learning-plan reviews with reviewed_at in the period (stamped by LearningPlanService::createReview). An instructor note is never a review. Reviews carry no due date — review overdue is deliberately not defined.',
                sourceDomain: 'Learning Plans (learning_plan_reviews)',
                timestampField: 'reviewed_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::milestoneReviewSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'plans_currently_review_due',
                label: 'Plans currently review-due',
                description: 'CURRENT-STATE plans in the review_due lifecycle status (set explicitly via markReviewDue — the only authoritative "review due" signal).',
                sourceDomain: 'Learning Plans (student_learning_plans)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['review_due'],
                excludedStatuses: ['draft', 'awaiting_assessment', 'active', 'paused', 'completed', 'archived'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['subject', 'education_level', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'LearningPlanAnalyticsRepository::milestoneReviewSummary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'homework_assigned',
                label: 'Homework assigned',
                description: 'Homework assignments created in the period (created_at). Assignment count — never a submission count.',
                sourceDomain: 'Homework (homework_assignments)',
                timestampField: 'created_at',
                includedStatuses: ['pending', 'submitted', 'graded'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['instructor', 'student'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'HomeworkAnalyticsRepository::summary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'homework_submitted',
                label: 'Homework submitted',
                description: 'Assignments with submitted_at in the period. One assignment has at most one submission in V1 (resubmission is rejected by SubmitHomeworkAction). Submission is NOT completion — grading is a separate state.',
                sourceDomain: 'Homework (homework_assignments)',
                timestampField: 'submitted_at',
                includedStatuses: ['submitted', 'graded'],
                excludedStatuses: ['pending'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['instructor', 'student'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'HomeworkAnalyticsRepository::summary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'homework_currently_overdue',
                label: 'Homework currently overdue',
                description: "AS-OF-NOW assignments still Pending with due_at in the past — the domain's own overdue predicate (HomeworkAssignment::scopeOverdue). Submitted and graded work is never overdue. Never mixed with period events.",
                sourceDomain: 'Homework (homework_assignments)',
                timestampField: 'n/a (current-state count against due_at)',
                includedStatuses: ['pending'],
                excludedStatuses: ['submitted', 'graded'],
                unit: MetricUnit::Count,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['instructor', 'student'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'HomeworkAnalyticsRepository::summary (Phase 18F).',
            ),
            new MetricDefinition(
                key: 'homework_on_time_submission_rate',
                label: 'Homework on-time submission rate',
                description: 'Among assignments whose due_at fell inside the period AND has already elapsed (observation complete), the share submitted at or before due_at. Null (never 0%) when no due date elapsed. Grading has no stored timestamp, so no review-time or period-scoped completion metric exists (§7.5 gate failed).',
                sourceDomain: 'Homework (homework_assignments)',
                timestampField: 'due_at (denominator) / submitted_at (numerator)',
                includedStatuses: ['pending', 'submitted', 'graded'],
                excludedStatuses: [],
                unit: MetricUnit::Percentage,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewLearningReports',
                supportedDimensions: ['instructor', 'student'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'HomeworkAnalyticsRepository::summary (Phase 18F).',
            ),

            // ── Phase 18G — Referrals, Quality & Communications ───────────
            new MetricDefinition(
                key: 'referral_wallet_credits',
                label: 'Referral wallet credits',
                description: 'Referral rewards actually credited: referral_credit wallet-ledger credits written in the period, counted and summed in minor units per currency (never cross-currency). A reward exists only when the ledger confirms it — no pending/approved referral state exists in Version 1.',
                sourceDomain: 'Wallet ledger (wallet_ledger_entries)',
                timestampField: 'created_at',
                includedStatuses: ['posted', 'reversed'],
                excludedStatuses: ['pending', 'failed'],
                unit: MetricUnit::MoneyMinor,
                sensitive: false,
                financial: true,
                requiredPermission: 'ViewReferralReports',
                supportedDimensions: ['currency'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::referralActivity (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'referral_credit_reversals',
                label: 'Referral credit reversals',
                description: 'Referral wallet credits later reversed (status flipped to Reversed), by entry created_at. An exception signal, never subtracted silently from credited totals.',
                sourceDomain: 'Wallet ledger (wallet_ledger_entries)',
                timestampField: 'created_at',
                includedStatuses: ['reversed'],
                excludedStatuses: ['posted', 'pending', 'failed'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: true,
                requiredPermission: 'ViewReferralReports',
                supportedDimensions: ['currency'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::referralActivity (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'review_submission_rate',
                label: 'Review submission rate',
                description: 'Among review eligibility windows opened in the period that have concluded (submitted, or expired by expires_at elapsing), the share submitted. Revoked and manual-review windows are excluded from the denominator. Null (never 0%) when no window has concluded.',
                sourceDomain: 'Reviews (lesson_review_eligibilities)',
                timestampField: 'opens_at (cohort) / used_at, expires_at (conclusion)',
                includedStatuses: ['open', 'used', 'expired'],
                excludedStatuses: ['revoked', 'manual_review'],
                unit: MetricUnit::Percentage,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewReviewQualityReports',
                supportedDimensions: ['instructor', 'lesson_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::reviewQualityRates (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'demo_review_rate',
                label: 'Demo review rate',
                description: 'The review submission rate restricted to demo-lesson eligibility windows (lesson_type = demo), identical definition and exclusions. Null at zero denominator.',
                sourceDomain: 'Reviews (lesson_review_eligibilities)',
                timestampField: 'opens_at (cohort) / used_at, expires_at (conclusion)',
                includedStatuses: ['open', 'used', 'expired'],
                excludedStatuses: ['revoked', 'manual_review'],
                unit: MetricUnit::Percentage,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewReviewQualityReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::reviewQualityRates (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'paid_lesson_review_rate',
                label: 'Paid-lesson review rate',
                description: 'The review submission rate restricted to paid-lesson eligibility windows (lesson_type = paid), identical definition and exclusions. Null at zero denominator.',
                sourceDomain: 'Reviews (lesson_review_eligibilities)',
                timestampField: 'opens_at (cohort) / used_at, expires_at (conclusion)',
                includedStatuses: ['open', 'used', 'expired'],
                excludedStatuses: ['revoked', 'manual_review'],
                unit: MetricUnit::Percentage,
                sensitive: true,
                financial: false,
                requiredPermission: 'ViewReviewQualityReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::reviewQualityRates (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'in_app_notifications_created',
                label: 'In-app notifications created',
                description: 'Database-channel notifications created in the period, broken down by notification class basename (never payload contents). The only notification channel with authoritative records in Version 1.',
                sourceDomain: 'Notifications (notifications table)',
                timestampField: 'created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewNotificationReports',
                supportedDimensions: ['type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::notificationActivity (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'in_app_read_rate',
                label: 'In-app read rate',
                description: 'Among in-app notifications created in the period, the share with read_at set as of now — an as-of-now read state over a period cohort, explicitly NOT a delivery rate (no delivery attempt model exists in Version 1). Null when none were created.',
                sourceDomain: 'Notifications (notifications table)',
                timestampField: 'created_at (cohort) / read_at (as-of-now state)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Percentage,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewNotificationReports',
                supportedDimensions: [],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::notificationActivity (Phase 18G).',
            ),
            new MetricDefinition(
                key: 'notification_dedup_claims',
                label: 'Notification duplicate-prevention claims',
                description: 'Dispatch idempotency-log rows claimed in the period, by notification class basename — each row is one deduplicated business notification (the unique idempotency key is the guarantee). Not a delivery outcome.',
                sourceDomain: 'Notifications (notification_dispatch_log)',
                timestampField: 'created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewNotificationReports',
                supportedDimensions: ['notification_class'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'ReferralCommunicationReportsRepository::notificationActivity (Phase 18G).',
            ),

            // ── Phase 18H — Marketplace supply & demand ───────────────────
            // The Executive KPI Overview adds NO metrics: it composes the
            // existing owners above without redefining anything.
            new MetricDefinition(
                key: 'instructor_supply_by_status',
                label: 'Instructor supply by lifecycle status',
                description: 'CURRENT-STATE instructor counts over the full InstructorStatus lifecycle (identical predicate to Phase 18D: user holding the instructor role, current profile status). Never a historical supply reconstruction.',
                sourceDomain: 'Users (user_profiles.instructor_status)',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['draft', 'submitted', 'under_review', 'documents_pending', 'interview_required', 'approved', 'active', 'vacation', 'suspended', 'archived', 'rejected'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMarketplaceReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'MarketplaceSupplyDemandRepository::supply (Phase 18H).',
            ),
            new MetricDefinition(
                key: 'active_instructors_by_subject',
                label: 'Active instructors by subject',
                description: 'Distinct currently-Active instructors per CURRENT teacher_subjects assignment — explicitly a current-state supply attribute, never historical supply.',
                sourceDomain: 'Users + teacher_subjects',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['active'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMarketplaceReports',
                supportedDimensions: ['subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'MarketplaceSupplyDemandRepository::supply (Phase 18H).',
            ),
            new MetricDefinition(
                key: 'active_instructors_without_availability',
                label: 'Active instructors without published availability',
                description: 'Currently-Active instructors with zero active teacher_availability windows — a current-state attention signal, never a utilization rate.',
                sourceDomain: 'Users + teacher_availability',
                timestampField: 'n/a (current-state count)',
                includedStatuses: ['active'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMarketplaceReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped.',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'MarketplaceSupplyDemandRepository::supply (Phase 18H).',
            ),
            new MetricDefinition(
                key: 'booking_demand_per_active_instructor',
                label: 'Booking demand per active instructor',
                description: 'Bookings created in the period ÷ currently-Active instructors — a plainly-labelled mixed-basis ratio (period events over a current-state denominator), null when no instructor is Active. Never a marketplace health score.',
                sourceDomain: 'Booking + Users',
                timestampField: 'bookings.created_at (numerator) / n/a (denominator)',
                includedStatuses: ['active'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMarketplaceReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnNull,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'MarketplaceSupplyDemandRepository::comparison (Phase 18H).',
            ),
            new MetricDefinition(
                key: 'subject_supply_demand_gaps',
                label: 'Subject supply/demand gaps',
                description: 'Subjects where period booking demand (Phase 18C basis: via lessons.subject_id) or current active-instructor assignment is zero — a bounded factual mismatch listing, never a score or ranking. Search events, profile views and waitlists do not exist and are never inferred.',
                sourceDomain: 'Booking + Users + teacher_subjects',
                timestampField: 'bookings.created_at (demand) / n/a (supply)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMarketplaceReports',
                supportedDimensions: ['subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'MarketplaceSupplyDemandRepository::comparison (Phase 18H).',
            ),
        ];
    }
}
