<?php

declare(strict_types=1);

namespace App\Reporting\Registry;

use App\Reporting\Contracts\MetricRegistryInterface;
use App\Reporting\DTOs\MetricDefinition;
use App\Reporting\Enums\MetricUnit;
use App\Reporting\Enums\ReportDataFreshness;
use App\Reporting\Enums\ZeroDenominatorPolicy;
use App\Reporting\Exceptions\DuplicateMetricKeyException;
use App\Reporting\Services\BookingLessonMeetingOperationsReportService;
use App\Reporting\Support\UniqueDefinitionKeys;

/**
 * The Version 1 metric catalogue (Phase 18B §11 / Phase 18C §15) —
 * metadata only, so two dashboards can never define the same named
 * KPI two different ways. Every metric here is now backed by a real
 * query in {@see BookingLessonMeetingOperationsReportService}
 * (`calculationOwner` names it) except `single_paid_bookings`/
 * `daily_recurring_bookings`/`weekly_recurring_bookings`, which became
 * calculable this phase via the new `bookings.recurrence_frequency`
 * column (Phase 18C data-provenance decision, Outcome B) — no metric
 * here is left `available`-adjacent while its calculation owner still
 * says GAP.
 *
 * `bookings_rescheduled` is new this phase (Outcome A, §6.2):
 * `booking_activities.action` is a structured, enum-typed column
 * (never free-text audit parsing) that already records every
 * `rescheduled` lifecycle event — no migration was needed for the
 * count itself, only a supporting index.
 */
final class MetricRegistry implements MetricRegistryInterface
{
    /** @var array<string, MetricDefinition> */
    private array $definitions;

    public function __construct()
    {
        $this->definitions = $this->buildDefinitions();
    }

    public function all(): array
    {
        return array_values($this->definitions);
    }

    public function find(string $key): ?MetricDefinition
    {
        return $this->definitions[$key] ?? null;
    }

    /** @return array<string, MetricDefinition> */
    private function buildDefinitions(): array
    {
        return UniqueDefinitionKeys::index(
            $this->definitionList(),
            fn (MetricDefinition $definition): string => $definition->key,
            fn (string $key) => throw DuplicateMetricKeyException::forKey($key),
        );
    }

    /** @return list<MetricDefinition> */
    private function definitionList(): array
    {
        return [
            new MetricDefinition(
                key: 'bookings_scheduled',
                label: 'Bookings scheduled',
                description: 'Every booking created in the period, regardless of eventual outcome.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor', 'booking_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->total (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'demo_bookings',
                label: 'Demo bookings',
                description: 'Bookings of the approved Version 1 "free_demo" booking type.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['free_demo'],
                excludedStatuses: ['paid_one_to_one'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byType[free_demo] (Phase 18C). BookingAnalyticsService\'s "demo requests/bookers" remains a separate, distinct KPI (conversion-funnel framing) — not duplicated, not replaced.',
            ),
            new MetricDefinition(
                key: 'paid_bookings',
                label: 'Paid bookings',
                description: 'Bookings of the approved Version 1 "paid_one_to_one" booking type.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one'],
                excludedStatuses: ['free_demo'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byType[paid_one_to_one] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'single_paid_bookings',
                label: 'Single paid bookings',
                description: 'Paid bookings that are not part of a recurring series (recurrence_frequency is null and no historical recurring_group marker).',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[single] (Phase 18C). Resolved via the new `bookings.recurrence_frequency` column (data-provenance Outcome B) — see RecurrenceClassifier. A booking created before this column existed that WAS part of a recurring series (detected via the pre-existing `meta->recurring_group` JSON key) is bucketed `unknown_historical`, never folded into this count.',
            ),
            new MetricDefinition(
                key: 'daily_recurring_bookings',
                label: 'Daily recurring bookings',
                description: 'Paid bookings belonging to a daily recurrence series.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one', 'daily'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[daily] (Phase 18C). Only bookings created after the recurrence_frequency column existed can be classified daily/weekly — historical rows fall into `unknown_historical` (see single_paid_bookings).',
            ),
            new MetricDefinition(
                key: 'weekly_recurring_bookings',
                label: 'Weekly recurring bookings',
                description: 'Paid bookings belonging to a weekly recurrence series.',
                sourceDomain: 'Booking',
                timestampField: 'created_at',
                includedStatuses: ['paid_one_to_one', 'weekly'],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byRecurrence[weekly] (Phase 18C). Same historical caveat as daily_recurring_bookings.',
            ),
            new MetricDefinition(
                key: 'bookings_rescheduled',
                label: 'Bookings rescheduled',
                description: 'Count of reschedule lifecycle events recorded in the period (a single booking rescheduled twice counts twice).',
                sourceDomain: 'Booking (booking_activities)',
                timestampField: 'created_at (of the activity row, not the booking)',
                includedStatuses: ['rescheduled'],
                excludedStatuses: ['requested', 'confirmed', 'cancelled', 'completed', 'no_show', 'guest_invited', 'guest_responded', 'payment_status_changed', 'meeting_linked'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['instructor', 'country', 'booking_type'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->rescheduled (Phase 18C). Data-provenance Outcome A (§6.2) — `booking_activities.action = \'rescheduled\'` is a structured, enum-typed, pre-existing column; no audit-message text parsing, no new schema concept, only a supporting index was added.',
            ),
            new MetricDefinition(
                key: 'lessons_completed',
                label: 'Lessons completed',
                description: 'Lessons whose finalized outcome is Completed.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['completed'],
                excludedStatuses: ['pending', 'student_no_show', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[completed] (Phase 18C). Authoritative source: `LessonOutcome::Completed` — never `LessonStatus::Completed` alone, which precedes finalization.',
            ),
            new MetricDefinition(
                key: 'lessons_scheduled',
                label: 'Lessons scheduled',
                description: 'Lessons whose scheduled start falls in the period, regardless of outcome yet (scheduled-activity view).',
                sourceDomain: 'Lessons',
                timestampField: 'starts_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewBookingLessonReports',
                supportedDimensions: ['country', 'subject', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->scheduled (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'student_no_shows',
                label: 'Student no-shows',
                description: 'Lessons whose finalized outcome is Student No-Show.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['student_no_show'],
                excludedStatuses: ['completed', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[student_no_show] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'instructor_no_shows',
                label: 'Instructor no-shows',
                description: 'Lessons whose finalized outcome is Instructor No-Show.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['instructor_no_show'],
                excludedStatuses: ['completed', 'student_no_show', 'both_absent', 'technical_issue', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[instructor_no_show] (Phase 18C). Also feeds `App\Quality`\'s existing InstructorNoShow/RepeatedInstructorNoShows detectors — reused, never recomputed independently.',
            ),
            new MetricDefinition(
                key: 'technical_issue_lessons',
                label: 'Technical-issue lessons',
                description: 'Lessons whose finalized outcome is Technical Issue.',
                sourceDomain: 'Lessons',
                timestampField: 'outcome_finalized_at',
                includedStatuses: ['technical_issue'],
                excludedStatuses: ['completed', 'student_no_show', 'instructor_no_show', 'both_absent', 'cancelled', 'pending'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->byOutcome[technical_issue] (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'disputed_lessons',
                label: 'Disputed lessons',
                description: 'Lessons currently under active dispute (LessonStatus::Disputed) — a snapshot of right now, not period-scoped; disputes can reopen any no-show/technical-issue decision, so this is distinct from technical_issue_lessons.',
                sourceDomain: 'Lessons',
                timestampField: 'n/a (current-state snapshot, like a Quality alert queue)',
                includedStatuses: ['disputed'],
                excludedStatuses: ['scheduled', 'live', 'completed', 'student_no_show', 'instructor_no_show', 'both_no_show', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: 'Not period-scoped — always "as of now".',
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->disputed (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'unfinalized_past_due_lessons',
                label: 'Unfinalized, past-due lessons',
                description: 'Lessons scheduled in the period whose end time has passed without a finalized outcome — an operational "stuck" indicator.',
                sourceDomain: 'Lessons',
                timestampField: 'starts_at (scoping) / ends_at (past-due test)',
                includedStatuses: ['pending'],
                excludedStatuses: ['completed', 'student_no_show', 'instructor_no_show', 'both_absent', 'technical_issue', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone for period scoping; 'past-due' itself compares against the server clock.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::lessonOutcomeSummary()->unfinalizedPastDue (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'cancelled_bookings',
                label: 'Cancelled bookings',
                description: 'Bookings cancelled in the period.',
                sourceDomain: 'Booking',
                timestampField: 'created_at (booking-created-in-period business-event view — status breakdown, not cancelled_at)',
                includedStatuses: ['cancelled'],
                excludedStatuses: ['pending', 'confirmed', 'completed', 'no_show'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewOperationalReports',
                supportedDimensions: ['country', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::bookingSummary()->byStatus[cancelled] (Phase 18C). BookingAnalyticsService\'s own "cancelled/cancellation rate" figure remains a separate, distinct KPI (conversion-funnel framing) — not duplicated, not replaced.',
            ),
            new MetricDefinition(
                key: 'meeting_creation_failures',
                label: 'Meeting creation failures',
                description: 'Meetings whose creation failed (booking_meetings.status = Failed).',
                sourceDomain: 'Booking (Meetings)',
                timestampField: 'booking_meetings.created_at',
                includedStatuses: ['failed'],
                excludedStatuses: ['pending', 'created', 'cancelled'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->failed (Phase 18C). Authoritative source corrected from the Phase 18B note: `bookings.meeting_status` no longer exists (dropped by migration 2026_07_19_100000) — the live authoritative column is `booking_meetings.status`, same `MeetingStatus::Failed` case.',
            ),
            new MetricDefinition(
                key: 'meetings_missing',
                label: 'Confirmed bookings missing a meeting',
                description: 'Confirmed bookings whose scheduled start falls in the period with no successfully-created meeting.',
                sourceDomain: 'Booking (Meetings)',
                timestampField: 'bookings.starts_at',
                includedStatuses: ['confirmed'],
                excludedStatuses: ['pending', 'cancelled', 'completed', 'no_show'],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->missingMeeting (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'student_joined_meetings',
                label: 'Student joined',
                description: 'Lessons in the period with at least one recorded student join event. A missing timestamp is "no evidence yet", never counted as absence.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping) / student_first_joined_at (evidence)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->studentJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'instructor_joined_meetings',
                label: 'Instructor joined',
                description: 'Lessons in the period with at least one recorded instructor join event.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping) / instructor_first_joined_at (evidence)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->instructorJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'both_joined_meetings',
                label: 'Both participants joined',
                description: 'Lessons in the period with recorded join evidence for both student and instructor.',
                sourceDomain: 'Lessons (lesson_attendance_records)',
                timestampField: 'lessons.starts_at (scoping)',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->bothJoined (Phase 18C).',
            ),
            new MetricDefinition(
                key: 'meeting_technical_issue_reports',
                label: 'Technical issue reports',
                description: 'Technical issue reports submitted in the period — a report count, not a distinct-affected-lesson count (one lesson may have more than one report).',
                sourceDomain: 'Lessons (lesson_technical_issue_reports)',
                timestampField: 'submitted_at',
                includedStatuses: [],
                excludedStatuses: [],
                unit: MetricUnit::Count,
                sensitive: false,
                financial: false,
                requiredPermission: 'ViewMeetingReports',
                supportedDimensions: ['instructor', 'student', 'subject'],
                zeroDenominatorPolicy: ZeroDenominatorPolicy::ReturnZero,
                timezoneBehavior: "Uses the report's reporting timezone.",
                freshness: ReportDataFreshness::Live,
                calculationOwner: 'BookingLessonMeetingOperationsReportService::meetingSummary()->technicalIssueReports (Phase 18C).',
            ),
        ];
    }
}
