<?php

declare(strict_types=1);

namespace App\Filament\Resources\AiQualityInsights\Schemas;

use App\Ai\Enums\AiFailureCode;
use App\Models\AiQualityInsight;
use App\Quality\Intelligence\Enums\QualityInsightStatus;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\HtmlString;

/**
 * The reading surface. Every design choice here pushes toward "a person
 * decides":
 *
 *  - an unmissable advisory banner above the AI text;
 *  - concerns rendered as questions to look into, never as findings;
 *  - confidence shown with its meaning spelled out, not as a score;
 *  - the source snapshot shown so an admin can check the AI's claims
 *    against the same numbers the reports show.
 *
 * The snapshot contains counts only — the review text the model saw is
 * never stored and so is never displayed here. An admin who wants the
 * reviews themselves reads them in the moderation queue, under that
 * surface's own access rules.
 */
class AiQualityInsightInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('AI-assisted — advisory only')
                ->description('This briefing was generated by an AI model from anonymized platform signals. It is not a finding, a rating, or a decision. Nothing in the platform acts on it: no status, alert, pay, or ranking changes as a result. Verify anything you intend to act on.')
                ->icon('heroicon-o-exclamation-triangle')
                ->schema([
                    Grid::make(3)->schema([
                        TextEntry::make('instructor.full_name')->label('Instructor'),
                        TextEntry::make('period_label')->label('Reporting period'),
                        TextEntry::make('status')
                            ->badge()
                            ->formatStateUsing(fn (QualityInsightStatus $state): string => $state->label())
                            ->color(fn (QualityInsightStatus $state): string => $state->color()),
                    ]),
                ]),

            Section::make('Failure')
                ->visible(fn (AiQualityInsight $record): bool => $record->status === QualityInsightStatus::Failed)
                ->schema([
                    TextEntry::make('failure_code')
                        ->label('Reason')
                        // A stable code, translated to a sentence — the
                        // provider's own message is never stored or shown.
                        ->formatStateUsing(fn (?string $state): string => $state === null
                            ? 'The insight could not be generated.'
                            : (AiFailureCode::tryFrom($state)?->label() ?? 'The insight could not be generated.'))
                        ->helperText('Nothing was stored from this run. You can generate the insight again once the cause is resolved.'),
                ]),

            Section::make('Summary')
                ->visible(fn (AiQualityInsight $record): bool => filled($record->summary))
                ->schema([
                    TextEntry::make('summary')->hiddenLabel()->prose(),
                ]),

            Section::make('Strengths')
                ->visible(fn (AiQualityInsight $record): bool => ($record->strengths ?? []) !== [])
                ->schema([
                    TextEntry::make('strengths')
                        ->hiddenLabel()
                        ->listWithLineBreaks()
                        ->bulleted(),
                ]),

            Section::make('Worth looking into')
                ->description('Questions raised by the data — not conclusions, and not evidence of a problem.')
                ->visible(fn (AiQualityInsight $record): bool => ($record->concerns ?? []) !== [])
                ->schema([
                    TextEntry::make('concerns')
                        ->hiddenLabel()
                        ->listWithLineBreaks()
                        ->bulleted(),
                ]),

            Section::make('Suggested next check')
                ->visible(fn (AiQualityInsight $record): bool => filled($record->recommended_review))
                ->schema([
                    TextEntry::make('recommended_review')->hiddenLabel()->prose(),
                ]),

            Section::make('How much weight to give this')
                ->visible(fn (AiQualityInsight $record): bool => $record->confidence !== null)
                ->schema([
                    TextEntry::make('confidence')
                        ->label('AI confidence')
                        ->formatStateUsing(fn (?float $state): string => $state === null ? '—' : round($state * 100).'%')
                        ->helperText('The model\'s own stated certainty, based mainly on how much data the period contained. It is not a measure of accuracy and never a quality score for the instructor.'),
                    TextEntry::make('requires_human_review')
                        ->label('Human review required')
                        ->formatStateUsing(fn (bool $state): string => $state ? 'Yes' : 'Not flagged — review anyway before acting'),
                ]),

            Section::make('What this was based on')
                ->description('The figures sent to the model, all of them produced by existing reports. Review text is never stored here.')
                ->collapsed()
                ->visible(fn (AiQualityInsight $record): bool => ($record->source_snapshot ?? []) !== [])
                ->schema([
                    TextEntry::make('source_snapshot')
                        ->hiddenLabel()
                        // Filament may hand this over as the raw JSON
                        // column value rather than the cast array,
                        // depending on how the entry resolves state.
                        ->formatStateUsing(fn (mixed $state): HtmlString => self::renderSnapshot(self::asArray($state))),
                ]),

            Section::make('Provenance')
                ->collapsed()
                ->schema([
                    Grid::make(3)->schema([
                        TextEntry::make('prompt_key')
                            ->label('Prompt')
                            ->formatStateUsing(fn (?string $state, AiQualityInsight $record): string => $state === null
                                ? '—'
                                : $state.':'.($record->prompt_version ?? '?')),
                        TextEntry::make('aiRun.model')->label('Model')->placeholder('—'),
                        TextEntry::make('aiRun.estimated_cost')
                            ->label('Estimated cost')
                            ->formatStateUsing(fn (?string $state, AiQualityInsight $record): string => $state === null
                                ? '—'
                                : $state.' '.($record->aiRun?->cost_currency ?? '')),
                    ]),
                    Grid::make(3)->schema([
                        TextEntry::make('requestedBy.full_name')->label('Requested by')->placeholder('—'),
                        TextEntry::make('created_at')->label('Generated')->dateTime(),
                        TextEntry::make('reviewed_at')->label('Reviewed')->dateTime()->placeholder('Not yet reviewed'),
                    ]),
                    TextEntry::make('review_note')
                        ->label('Reviewer note')
                        ->placeholder('—')
                        ->visible(fn (AiQualityInsight $record): bool => filled($record->review_note)),
                ]),
        ]);
    }

    /** @return array<string, mixed> */
    private static function asArray(mixed $state): array
    {
        if (is_array($state)) {
            return $state;
        }

        if (is_string($state)) {
            $decoded = json_decode($state, true);

            return is_array($decoded) ? $decoded : [];
        }

        return [];
    }

    /** @param array<string, mixed> $snapshot */
    private static function renderSnapshot(array $snapshot): HtmlString
    {
        $html = '<dl class="text-sm space-y-1">';

        foreach (['statistics', 'dimension_ratings', 'tag_counts'] as $group) {
            foreach ((array) ($snapshot[$group] ?? []) as $label => $value) {
                $html .= sprintf('<div><span class="font-medium">%s:</span> %s</div>', e((string) $label), e((string) $value));
            }
        }

        $html .= sprintf(
            '<div><span class="font-medium">Reviews in period:</span> %d (%d excerpts sent)</div></dl>',
            (int) ($snapshot['reviews_in_period'] ?? 0),
            (int) ($snapshot['excerpts_sent'] ?? 0),
        );

        return new HtmlString($html);
    }
}
