<?php

declare(strict_types=1);

namespace App\Notifications\Auth;

use App\Notifications\Concerns\ConfiguresTransactionalEmail;
use App\Notifications\Contracts\TransactionalEmail;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Delivers the one-time code that verifies an email address.
 *
 * The plain code is carried on the notification (never persisted — only
 * its hash is, on the challenge row) and is generated by
 * EmailVerificationOtpService, which owns the challenge lifecycle.
 */
final class EmailVerificationCodeNotification extends Notification implements ShouldQueue, TransactionalEmail
{
    use ConfiguresTransactionalEmail, Queueable;

    public function __construct(
        public readonly string $code,
        public readonly int $expiresInMinutes,
    ) {
        $this->queue = 'notifications';
        $this->afterCommit();
    }

    /** @return array<int, string> */
    public function via(mixed $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(mixed $notifiable): MailMessage
    {
        return $this->configureMailMessage(new MailMessage)
            ->subject('Your verification code — '.config('app.name'))
            ->view('emails.auth.verify-email-code', [
                'code' => $this->code,
                'notifiable' => $notifiable,
                'appName' => config('app.name'),
                'appUrl' => config('app.url'),
                'expiry' => $this->expiresInMinutes,
            ]);
    }

    public function emailCategory(): string
    {
        return 'auth';
    }

    public function senderKey(): string
    {
        return 'auth';
    }
}
