<?php

declare(strict_types=1);

namespace Tests\Feature\Academic;

use App\Curriculum\Exceptions\AcademicContextException;
use App\Curriculum\Services\EducationSystemService;
use App\Enums\AcademicStatus;
use App\Exceptions\HistoricalRecordCannotBeDeletedException;
use App\Models\AcademicCategory;
use App\Models\AcademicLevel;
use App\Models\Country;
use App\Models\CountryEducationSystem;
use App\Models\Curriculum;
use App\Models\EducationSystem;
use App\Models\Subject;
use App\Models\User;
use Database\Seeders\AcademicPermissionSeeder;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Validation\ValidationException;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class EducationSystemTest extends TestCase
{
    use RefreshDatabase;

    private User $manager;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(AcademicPermissionSeeder::class);

        $role = Role::firstOrCreate(['name' => 'manager', 'guard_name' => 'web']);
        $this->manager = User::factory()->create(['status' => 'active']);
        $this->manager->assignRole($role);
    }

    private function service(): EducationSystemService
    {
        return app(EducationSystemService::class);
    }

    private function subject(string $slug = 'mathematics'): Subject
    {
        $category = AcademicCategory::query()->firstOrCreate(['slug' => 'school'], ['name' => 'School']);

        return Subject::create([
            'academic_category_id' => $category->id,
            'name' => ucfirst($slug),
            'slug' => $slug,
        ]);
    }

    private function level(string $slug = 'high-school'): AcademicLevel
    {
        return AcademicLevel::create([
            'name' => ucfirst(str_replace('-', ' ', $slug)),
            'slug' => $slug,
        ]);
    }

    // ── EducationSystem CRUD ─────────────────────────────────────────────

    public function test_manager_can_create_education_system(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, [
            'name' => 'CBSE',
            'slug' => 'cbse',
        ]);

        $this->assertDatabaseHas('education_systems', ['slug' => 'cbse', 'status' => 'active']);
        $this->assertSame(AcademicStatus::Active, $system->status);
    }

    public function test_manager_can_update_education_system(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'IB', 'slug' => 'ib']);

        $updated = $this->service()->updateEducationSystem($this->manager, $system, [
            'status' => AcademicStatus::Inactive->value,
        ]);

        $this->assertSame(AcademicStatus::Inactive, $updated->status);
    }

    public function test_duplicate_slug_is_rejected(): void
    {
        $this->service()->createEducationSystem($this->manager, ['name' => 'GCSE', 'slug' => 'gcse']);

        $this->expectException(ValidationException::class);

        $this->service()->createEducationSystem($this->manager, ['name' => 'GCSE Two', 'slug' => 'gcse']);
    }

    public function test_education_system_can_be_soft_deleted_and_restored(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'AP', 'slug' => 'ap']);

        $system->delete();
        $this->assertSoftDeleted('education_systems', ['id' => $system->id]);

        $system->restore();
        $this->assertDatabaseHas('education_systems', ['id' => $system->id, 'deleted_at' => null]);
    }

    /**
     * Phase 1.1 historical safety: EducationSystem is now a master
     * reference that other academic domains will snapshot by id, so
     * forceDelete() must be blocked even though a "ForceDelete:
     * EducationSystem" permission is auto-generated by the seeder.
     */
    public function test_education_system_cannot_be_force_deleted(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'IB', 'slug' => 'ib-hard-delete']);

        $this->expectException(HistoricalRecordCannotBeDeletedException::class);

        $system->forceDelete();
    }

    /**
     * Force-deletion is blocked before the DB-level cascadeOnDelete on
     * country_education_system / education_system_academic_level /
     * curriculum_education_system ever fires, so those mappings cannot
     * disappear as a side effect of destroying the master record.
     */
    public function test_education_system_mappings_survive_a_blocked_force_delete_attempt(): void
    {
        $country = Country::factory()->create();
        $level = AcademicLevel::create(['name' => 'Grade 10', 'slug' => 'grade-10-fd']);
        $category = AcademicCategory::query()->firstOrCreate(['slug' => 'school'], ['name' => 'School']);
        $subject = Subject::create(['academic_category_id' => $category->id, 'name' => 'Physics FD', 'slug' => 'physics-fd']);
        $curriculum = Curriculum::create([
            'subject_id' => $subject->id,
            'academic_level_id' => $level->id,
            'name' => 'Physics FD Curriculum',
            'slug' => 'physics-fd-curriculum',
        ]);

        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE FD', 'slug' => 'cbse-fd']);
        $this->service()->mapToCountry($this->manager, $system, $country);
        $this->service()->mapToAcademicLevel($this->manager, $system, $level);
        $this->service()->mapToCurriculum($this->manager, $system, $curriculum);

        try {
            $system->forceDelete();
        } catch (HistoricalRecordCannotBeDeletedException) {
            // expected
        }

        $this->assertDatabaseHas('country_education_system', ['education_system_id' => $system->id]);
        $this->assertDatabaseHas('education_system_academic_level', ['education_system_id' => $system->id]);
        $this->assertDatabaseHas('curriculum_education_system', ['education_system_id' => $system->id]);
        $this->assertDatabaseHas('education_systems', ['id' => $system->id]);
    }

    // ── Country mapping ──────────────────────────────────────────────────

    public function test_country_may_have_multiple_education_systems(): void
    {
        $country = Country::factory()->create();
        $systemA = $this->service()->createEducationSystem($this->manager, ['name' => 'System A', 'slug' => 'system-a']);
        $systemB = $this->service()->createEducationSystem($this->manager, ['name' => 'System B', 'slug' => 'system-b']);

        $this->service()->mapToCountry($this->manager, $systemA, $country);
        $this->service()->mapToCountry($this->manager, $systemB, $country);

        $this->assertCount(2, $country->educationSystemMappings()->get());
    }

    public function test_education_system_may_belong_to_multiple_countries(): void
    {
        $countryA = Country::factory()->create();
        $countryB = Country::factory()->create();
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'International', 'slug' => 'international']);

        $this->service()->mapToCountry($this->manager, $system, $countryA);
        $this->service()->mapToCountry($this->manager, $system, $countryB);

        $this->assertCount(2, $system->countryMappings()->get());
    }

    public function test_duplicate_country_mapping_is_rejected(): void
    {
        $country = Country::factory()->create();
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);

        $this->service()->mapToCountry($this->manager, $system, $country);

        $this->expectException(AcademicContextException::class);
        $this->service()->mapToCountry($this->manager, $system, $country);
    }

    public function test_duplicate_country_mapping_is_rejected_at_database_level(): void
    {
        $country = Country::factory()->create();
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);

        $this->service()->mapToCountry($this->manager, $system, $country);

        $this->expectException(QueryException::class);

        CountryEducationSystem::query()->create([
            'country_id' => $country->id,
            'education_system_id' => $system->id,
        ]);
    }

    public function test_country_mapping_can_be_removed(): void
    {
        $country = Country::factory()->create();
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);
        $mapping = $this->service()->mapToCountry($this->manager, $system, $country);

        $this->service()->unmapFromCountry($this->manager, $mapping);

        $this->assertDatabaseMissing('country_education_system', ['id' => $mapping->id]);
    }

    // ── Academic Level mapping ───────────────────────────────────────────

    public function test_system_may_contain_multiple_levels_and_level_may_map_to_multiple_systems(): void
    {
        $systemA = $this->service()->createEducationSystem($this->manager, ['name' => 'System A', 'slug' => 'system-a']);
        $systemB = $this->service()->createEducationSystem($this->manager, ['name' => 'System B', 'slug' => 'system-b']);
        $levelA = $this->level('level-a');
        $levelB = $this->level('level-b');

        $this->service()->mapToAcademicLevel($this->manager, $systemA, $levelA);
        $this->service()->mapToAcademicLevel($this->manager, $systemA, $levelB);
        $this->service()->mapToAcademicLevel($this->manager, $systemB, $levelA);

        $this->assertCount(2, $systemA->academicLevelMappings()->get());
        $this->assertCount(2, $levelA->educationSystemMappings()->get());
    }

    public function test_duplicate_level_mapping_is_rejected(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);
        $level = $this->level();

        $this->service()->mapToAcademicLevel($this->manager, $system, $level);

        $this->expectException(AcademicContextException::class);
        $this->service()->mapToAcademicLevel($this->manager, $system, $level);
    }

    // ── Curriculum mapping ───────────────────────────────────────────────

    public function test_curriculum_can_be_associated_with_education_system(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);
        $curriculum = Curriculum::factory()->create();

        $this->service()->mapToCurriculum($this->manager, $system, $curriculum);

        $this->assertCount(1, $curriculum->educationSystemMappings()->get());
    }

    public function test_duplicate_curriculum_mapping_is_rejected(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);
        $curriculum = Curriculum::factory()->create();

        $this->service()->mapToCurriculum($this->manager, $system, $curriculum);

        $this->expectException(AcademicContextException::class);
        $this->service()->mapToCurriculum($this->manager, $system, $curriculum);
    }

    public function test_curriculum_mapping_can_be_removed(): void
    {
        $system = $this->service()->createEducationSystem($this->manager, ['name' => 'CBSE', 'slug' => 'cbse']);
        $curriculum = Curriculum::factory()->create();
        $mapping = $this->service()->mapToCurriculum($this->manager, $system, $curriculum);

        $this->service()->unmapFromCurriculum($this->manager, $mapping);

        $this->assertDatabaseMissing('curriculum_education_system', ['id' => $mapping->id]);
    }

    // ── Authorization ─────────────────────────────────────────────────────

    public function test_unauthorized_user_cannot_create_education_system(): void
    {
        $student = User::factory()->create(['status' => 'active']);

        $this->expectException(AuthorizationException::class);
        $this->service()->createEducationSystem($student, ['name' => 'CBSE', 'slug' => 'cbse']);
    }
}
