<?php

declare(strict_types=1);

namespace App\Policies;

use App\Models\ReferralCode;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;
use Spatie\Permission\Exceptions\PermissionDoesNotExist;

/**
 * Read access via ViewReferralCodes; disabling authorizes
 * DisableReferralCodes inside ReferralCodeService::disable(). No
 * create/edit/delete/re-enable surface — codes are generated by the
 * domain, disabled as an abuse response, and preserved forever.
 */
class ReferralCodePolicy
{
    use HandlesAuthorization;

    public function viewAny(User $user): bool
    {
        return $this->hasPermission($user, 'ViewReferralCodes');
    }

    public function view(User $user, ReferralCode $code): bool
    {
        return $this->hasPermission($user, 'ViewReferralCodes');
    }

    public function create(User $user): bool
    {
        return false;
    }

    public function update(User $user, ReferralCode $code): bool
    {
        return false;
    }

    public function delete(User $user, ReferralCode $code): bool
    {
        return false;
    }

    public function forceDelete(User $user, ReferralCode $code): bool
    {
        return false;
    }

    private function hasPermission(User $user, string $permission): bool
    {
        try {
            return $user->hasPermissionTo($permission);
        } catch (PermissionDoesNotExist) {
            return false;
        }
    }
}
